---
title: "BB1 plots"
author: "Tin"
date: "05/05/2021"
output: 
  html_document: 
    toc: true
    toc_float: true
    toc_collapsed: true
    toc_depth: 3
  theme: lumen

---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

library(plyr)
library(dplyr)
library(ggplot2)
library(lubridate)
library(naniar)
library(tidyr)
library(plotly)
library(knitr)
library(data.table)
library(kableExtra)
library(ggsci)
library(effects)
library(tidyverse)
library(zoo)
library(caret)
library(ggpubr)
library(gridExtra)
library(lognorm)
library(reshape2)
library(matrixStats)
library(gtools)

```







```{r read data, include = F, message = F, warning = F}

# define directory

dir_rf <- "G:\\.shortcut-targets-by-id\\1txCh9lZ7VGCujXGvBaJCMVnuxT-65q4K\\Micromet Lab\\Projects\\2014-Burns Bog\\Flux-tower\\flux_data\\for_uncertainty\\RF_results"

dir_unc <- "G:\\.shortcut-targets-by-id\\1txCh9lZ7VGCujXGvBaJCMVnuxT-65q4K\\Micromet Lab\\Projects\\2014-Burns Bog\\Flux-tower\\flux_data\\for_uncertainty"

## read random forest gap-filled NEE result (already averaged)
RF_NEE <- readRDS(paste0(dir_rf,"/BB_NEE_rf_result_for_uncertainty"))

## read NEE RF gapfilling with 20x iteration
result_RF_NEE <- readRDS(paste0(dir_rf,"/BB_NEE_rf_result"))

## read CH4 RF gapfilling with 20x iteration
result_RF_FCH4 <- read_csv(paste0(dir_rf,"/BB_FCH4_rf_result.csv"))

## read REddyProcOuput 
REddyProcOutput<- readRDS(paste0(dir_unc,"/ReddyProcOutput"))
REddyProcOutput_ori <- REddyProcOutput
REddyProcOutput <- REddyProcOutput$sTEMP
REddyProcOutput$date <- as.Date(REddyProcOutput$sDateTime, format="%Y-%m-%d %H:%M:%S")


# read flux & met data
BB1 <- fread(paste0(dir_unc,"/BB_L3.csv"))
BB1[BB1 == -9999] <- NA
BB1$DATE <- as.POSIXct(BB1$DATE, tz = "UTC")
BB1$date <- as.Date(BB1$DATE, format="%Y-%m-%d %H:%M:%S")

BB1 <- BB1 %>%
  mutate(period = NA, 
         season = NA)


# filter date
BB1 <- BB1 %>% 
  filter(DATE >= as.POSIXct("2015-10-01 00:30:00", tz = "UTC") & DATE < as.POSIXct("2021-10-01 00:00:00", tz = "UTC")) 
REddyProcOutput <- REddyProcOutput %>% 
  filter(date >= "2015-10-01" & date < "2021-10-01") 


# function for setting year period
set_period <- function(data) {
  y_2015_2016 <- data$date >= "2015-10-01" & data$date < "2016-10-01"
  y_2016_2017 <- data$date >= "2016-10-01" & data$date < "2017-10-01"
  y_2017_2018 <- data$date >= "2017-10-01" & data$date < "2018-10-01"
  y_2018_2019 <- data$date >= "2018-10-01" & data$date < "2019-10-01"
  y_2019_2020 <- data$date >= "2019-10-01" & data$date < "2020-10-01"
  y_2020_2021 <- data$date >= "2020-10-01" & data$date < "2021-10-01"
  
  data$period[y_2015_2016] <- "2015-2016"
  data$period[y_2016_2017] <- "2016-2017"
  data$period[y_2017_2018] <- "2017-2018"
  data$period[y_2018_2019] <- "2018-2019"
  data$period[y_2019_2020] <- "2019-2020"
  data$period[y_2020_2021] <- "2020-2021"
  
  data
}

#Conversion factors
ch4_conv <- 12.01/(10^6)
co2_conv <- 12.01/(10^6) 
d.avg <- 1800 * 48  # 60s * 30min * 2 hours * 24 hours



```

```{r data wrangling and function , include = F, message = F, warning = F}
# fill long gaps after MDS gapfilling with values from random forest gapfilling
long_gap2 <- BB1$DATE >= as.POSIXct("2015-12-01 00:30:00", tz = "UTC") &
  BB1$DATE < as.POSIXct("2016-02-21 00:30:00", tz = "UTC")
long_gap <- BB1$DATE >= as.POSIXct("2016-10-22 00:30:00", tz = "UTC") &
  BB1$DATE < as.POSIXct("2017-01-21 00:30:00", tz = "UTC")


BB1$NEE_RF <- RF_NEE$NEE_RF_filled  # random forest gapfill
BB1$NEE_f_RF <- BB1$NEE_f
BB1$NEE_RF_fsd <- RF_NEE$NEE_RF_filled_SD

# fill all NA values with values from random forest
BB1$NEE_f_RF[long_gap] <- BB1$NEE_RF[long_gap]
BB1$NEE_f_RF[long_gap2] <- BB1$NEE_RF[long_gap2]


# check if there are still gaps
which(is.na(BB1$NEE_f_RF))


BB1$GPP_f_RF <- BB1$Reco - BB1$NEE_f_RF




########### BB flux ############

# BB_flux <- BB1 %>%
#   select (c(DATE, date, jday, month_local, Year_local, time, period, season,
#             Tau, ET, RH, u., jday, co2_flux, ch4_flux, NEE_f,
#             Reco, GPP_f, GPP_DT, Reco_DT, FCH4_f, FCH4_gf_RF,
#             NEE_f_RF, GPP_f_RF)) %>%
#   dplyr::rename(year_local = Year_local)

BB_flux <- BB1 %>%
  select (c(DATE, date, jday, month_local, Year_local, time, period, season,
            Tau, ET, RH, u., jday, co2_flux, ch4_flux, NEE_f,
            Reco, GPP_f, GPP_DT, Reco_DT, FCH4_f)) %>%
  dplyr::rename(year_local = Year_local)


# function 
plot_daily <- function(data, variable, label, ma = 15) {
  # browser()
  if(ma == 1) {
    data %>% 
    ggplot() +
    geom_line(aes(x = date, y = {{variable}}), col = "navy") +
    labs(x = "year", 
         y = label) +
    # theme(legend.position="none") +
    theme_bw()
  } else {
    data %>% 
    ggplot() +
    geom_point(aes(x = date, y = {{variable}}, col = "daily")) +
    geom_line(aes(x = date, y = rollmean({{variable}}, ma, fill = NA), col = "smoothed")) +
    scale_color_manual(values = c("daily" = "lightblue", 
                                  "smoothed" = "navy")) +
    labs(x = "year", 
         y = label, 
         colour = "") +
    theme_bw()  
  }
}

plot_monthly <- function(main_data, mean_data){
  main_data%>%
  ggplot() +
    geom_bar(aes(x = month, y = value, fill = as.factor(period)), 
             position = position_dodge(), stat="identity") +
    geom_line(data = mean_data, aes(x = month, y = value, group = 1)) +
    geom_point(data = mean_data, aes(x = month, y = value, group = 1)) +
    facet_wrap(vars(variable_lab), ncol = 1,
               scales = "free_y",
               strip.position = "left", 
               # labeller = label_parsed
               ) +
    labs(x = "", y = "", fill = "Year") +
    theme_bw()+
    theme(strip.background = element_blank(),
          strip.placement = "outside") 
}

plot_monthly_anom <- function(main_data, anom_data){
  main_data%>%
  ggplot() +
    geom_bar(data= anom_data, aes(x = month, y = value), 
             position = position_dodge(), stat="identity") +
    geom_line(aes(x = month, y = value, group = 1)) +
    facet_wrap(vars(variable_lab), ncol = 1,
               scales = "free_y",
               strip.position = "left", 
               # labeller = label_parsed
               ) +
    # labs(x = "", y = "", fill = "Year") +
    scale_y_continuous(name = "", 
      sec.axis = sec_axis(~./2, name = "Productivity % of best", 
        labels = "")
      ) +
    theme_bw()+
    theme(strip.background = element_blank(),
          strip.placement = "outside") 
}

```


```{r Data wrangling for fluxes, include = F, message = F, warning = F}
#Conversion factors
ch4_conv <- 12.01/(10^6)
co2_conv <- 12.01/(10^6) 
d.avg <- 1800 * 48  # 60s * 30min * 2 hours * 24 hours

#TO FILTER NON GF DATA TO DAYS WHERE ONLY 60% OR MORE IS PRESENT
daily.nGF <- BB_flux %>%
  dplyr::select(c(year_local, jday, month_local, co2_flux, ch4_flux)) %>%
  drop_na()

obs_count <- daily.nGF %>% 
  group_by(year_local, jday) %>% 
  tally() %>% 
  ungroup()

daily.nGF <- daily.nGF %>%
  group_by(year_local, jday) %>% 
  summarize(co2 = mean(co2_flux),
            ch4 = mean(ch4_flux)) %>%
  mutate(co2gC = co2 * d.avg * co2_conv) %>%
  mutate(ch4gC = ch4* d.avg * co2_conv) %>%
  mutate(ch4mgC = ch4gC * 1000) %>% 
  ungroup() %>% 
  mutate(n = obs_count$n) %>% 
  # filter(n > 48 * 0.6) %>% 
  mutate(date = as.POSIXct(paste(year_local, jday, sep = "-"), format = "%Y-%j"))

daily.nGF[which(daily.nGF$n > 48 * 0.6), 2:6] <- NA

  
# daily.nGF$month_local <- as.factor(daily.nGF$month_local)

daily <- BB_flux %>%
  ddply("date", summarize,
            NEE_f = mean(NEE_f),
            NEE_f_RF = mean(NEE_f_RF),
            GPP_DT = mean(GPP_DT),
            GPP_f = mean(GPP_f),
            GPP_f_RF = mean(GPP_f_RF),
            Reco = mean(Reco),
            Reco_DT = mean(Reco_DT),
            CH4_f_RF = mean(FCH4_gf_RF),
            CH4_f = mean(FCH4_f)) %>%
  mutate(NEEgC_f = NEE_f * d.avg * co2_conv, 
         NEEgC_f_RF = NEE_f_RF * d.avg * co2_conv,
         GPPgC_DT = GPP_DT * d.avg * co2_conv, 
         GPPgC_f = GPP_f *d.avg * co2_conv,
         GPPgC_f_RF = GPP_f_RF * d.avg * co2_conv,
         RecogC = Reco * d.avg * co2_conv, 
         RecogC_DT = Reco_DT * d.avg * co2_conv,
         CH4gC_f = CH4_f * d.avg * ch4_conv, 
         CH4mgC_f = CH4gC_f * 1000,
         CH4gC_f_RF = CH4_f_RF * d.avg * ch4_conv,
         CH4mgC_f_RF = CH4gC_f_RF * 1000,
         year_local = year(date), 
         month_local = month(date), 
         floor_date = floor_date(date, "month"))



# set year period
y_2015_2016 <- daily$date >= "2015-06-20" & daily$date < "2016-06-20"
y_2016_2017 <- daily$date >= "2016-06-20" & daily$date < "2017-06-20"
y_2017_2018 <- daily$date >= "2017-06-20" & daily$date < "2018-06-20"
y_2018_2019 <- daily$date >= "2018-06-20" & daily$date < "2019-06-20"
y_2019_2020 <- daily$date >= "2019-06-20" & daily$date < "2020-06-20"
y_2020_2021 <- daily$date >= "2020-06-20" & daily$date < "2021-06-20"



daily$period[y_2015_2016] <- "2015-2016"
daily$period[y_2016_2017] <- "2016-2017"
daily$period[y_2017_2018] <- "2017-2018"
daily$period[y_2018_2019] <- "2018-2019"
daily$period[y_2019_2020] <- "2019-2020"
daily$period[y_2020_2021] <- "2020-2021"

# set season 
GS <- daily$month_local %in% c(4, 5, 6, 7, 8, 9)
NGS <- daily$month_local %in% c(10, 11, 12, 1, 2, 3)
daily$season[GS] <- "growing season"
daily$season[NGS] <- "non-growing season"

cumsum <- daily %>% 
  group_by(period) %>% 
  arrange(date) %>% 
  mutate(cumNEE = cumsum(NEEgC_f), 
         cumNEE_RF = cumsum(NEEgC_f_RF),
         cumReco = cumsum(RecogC),
         cumGPP = cumsum(GPPgC_f), 
         cumGPP_RF = cumsum(GPPgC_f_RF),
         cumCH4 = cumsum(CH4gC_f_RF)
         ) %>% 
  ungroup()

monthly <- daily %>% 
   ddply(c("floor_date"), summarize,
        length = length(NEEgC_f),
        NEEgC_f = mean(NEEgC_f) * length, # * length(NEEgC_f) for month^-1
        NEEgC_f_RF = mean(NEEgC_f_RF)* length,
        GPPgC_f = mean(GPPgC_f)* length,
        GPPgC_f_RF = mean(GPPgC_f_RF)* length,
        RecogC = mean(RecogC)* length,
        CH4gC_f = mean(CH4gC_f)* length,
        CH4gC_f_RF = mean(CH4gC_f_RF)* length) %>% 
  mutate(month_local = month(floor_date))

monthly_means <- monthly %>% 
  ddply("month_local", summarize, 
       NEEgC_f = mean(NEEgC_f, na.rm = T),
       NEEgC_f_RF = mean(NEEgC_f_RF, na.rm = T), 
       GPPgC_f = mean(GPPgC_f, na.rm = T),
       GPPgC_f_RF = mean(GPPgC_f_RF, na.rm = T), 
       RecogC = mean(RecogC, na.rm = T),
       CH4gC_f = mean(CH4gC_f, na.rm = T),
       CH4gC_f_RF = mean(CH4gC_f_RF, na.rm = T))
# daily$month_local <- as.factor(daily$month_local)

monthly_anom <- monthly
for(i in 1:nrow(monthly)){ 
  monthly_anom[i, c(3:8)] <- monthly_anom[i, c(3:8)] -  
    monthly_means[monthly$month_local[i], c(2:7)]
  }

# dailyGS <- daily[(daily$jday >= 92 & daily$jday <= 274), ] 
# dailyNGS <-daily[(daily$jday < 92 | daily$jday >=275), ] 


# Cbudget <- daily %>%
#   dplyr::select(c(Site, month_local, jday, CH4mgC_f_RF, CH4gC_f_RF, NEEgC_f)) %>%
#   group_by(Site, month_local) %>%
#   summarise(CH4gCcum = cumsum(CH4gC_f_RF),
#             CH4mgcum = cumsum(CH4mgC_f_RF),
#             NEEgCcum = cumsum(NEEgC_f),
#             NEEgC = NEEgC_f,
#             CH4gC = CH4gC_f_RF,
#             CH4mgC = CH4mgC_f_RF,
#             jday = jday)
```


```{r wrangling for uncertainty analysis}

###### wrangling REddyProcOutput ######

REddyProcOutput <- REddyProcOutput %>% 
  mutate(date = as.Date(as.POSIXct(sDateTime - 15*60))) %>% # midnight belongs to the previous
  mutate(year_local = year(date), 
         month_local = month(date), 
         floor_date = floor_date(date, "month")
  ) %>% 
  rename(ustar_season = season) %>% 
  set_period()

```


```{r uncertainty analysis}

# set season 
GS <- REddyProcOutput$month_local %in% c(4, 5, 6, 7, 8, 9)
NGS <- REddyProcOutput$month_local %in% c(10, 11, 12, 1, 2, 3)
REddyProcOutput$season[GS] <- "growing season"
REddyProcOutput$season[NGS] <- "non-growing season"

## summary
summary(REddyProcOutput$NEE_fsd)
plot(NEE_fsd ~ NEE_fall, slice(REddyProcOutput, sample.int(nrow(REddyProcOutput),400)))


####################### Random Uncertainty ##########################

# for random uncertainty, we only do it for NEE. No random uncertainty calculation for GPP & Reco in REddyProc


# First we need to quantify the error terms, i.e. model-data residuals. For all the records of good quality, we have an original measured value NEE_uStar_orig and modelled value from MDS gapfilling, NEE_uStar_fall. The residual of bad-quality data is set to missing.

REddyProcOutput <- REddyProcOutput %>%
  mutate(
    resid = ifelse(NEE_fqc == 0, NEE_orig - NEE_fall, NA )
  )

# #Now we can inspect the the autocorrelation of the errors.
 
acf(REddyProcOutput$resid, na.action = na.pass, main = "")

# Computation of effective number of observations is provided by function computeEffectiveNumObs from package lognorm based on the empirical autocorrelation function for given model-data residuals.

autoCorr <- computeEffectiveAutoCorr(REddyProcOutput$resid)
nEff <- computeEffectiveNumObs(REddyProcOutput$resid, na.rm = T)
c(nEff = nEff, nObs = sum(is.finite(REddyProcOutput$resid)))
#Now we can use the formulas for the sum and the mean of correlated normally distributed variables to compute the uncertainty of the mean.


#----- Daily Aggregation for random uncertainty ------#


aggDayRand <- REddyProcOutput %>% 
  ddply("date", summarize, 
        DateTime = first(sDateTime), 
        nRec = sum(NEE_fqc == 0, na.rm = TRUE),
        nEff = computeEffectiveNumObs(resid, effAcf = !!autoCorr, na.rm = TRUE),
        NEE = mean(NEE_f, na.rm = TRUE)* d.avg * co2_conv,
        sdNEE = if (nEff <= 1)
          NA_real_
          else sqrt(mean(NEE_fsd^2, na.rm = TRUE) / (nEff - 1)* d.avg * co2_conv),
        sdNEEuncorr = if (nRec == 0)
          NA_real_
        else sqrt(mean(NEE_fsd^2, na.rm = TRUE) / (nRec - 1)* d.avg * co2_conv)
        ) %>% 
  mutate( 
    NEE_U = NEE + sdNEE, 
    NEE_L = NEE - sdNEE)


# Plot daily random uncertainty

(aggDayRand %>% 
  filter(date >= "2020-03-01" & date <= "2020-05-01") %>%
  ggplot(aes(x = date, y = NEE)) +
    geom_line() +
    geom_ribbon(aes(ymin = NEE_L, ymax = NEE_U), 
              alpha=0.1, 
              linetype="dashed",
              color="grey") +
    labs(x = "year", 
         y = bquote('NEE (g C' ~m^-2~ day^-1*')'), 
         colour = "") +
    theme_bw())


#--------- annual aggregation for random uncertainty ---------#


aggAnnualRand <- REddyProcOutput %>% 
  ddply("period", summarize, 
        DateTime = first(sDateTime), 
        nRec = sum(NEE_fqc == 0, na.rm = TRUE),
        nEff = computeEffectiveNumObs(resid, effAcf = !!autoCorr, na.rm = TRUE),
        NEE = mean(NEE_f, na.rm = TRUE)* d.avg * co2_conv * 365,
        sdNEE = if (nEff <= 1)
          NA_real_
          else sqrt(mean(NEE_fsd^2, na.rm = TRUE) / (nEff - 1)* d.avg * co2_conv * 365),
        sdNEEuncorr = if (nRec == 0)
          NA_real_
        else sqrt(mean(NEE_fsd^2, na.rm = TRUE) / (nRec - 1)* d.avg * co2_conv * 365)
        ) %>% 
  mutate( 
    NEE_U = NEE + sdNEE, 
    NEE_L = NEE - sdNEE)


# note: GPP and Reco don't have random uncertainty because their fsd are not calculated in REddyPro


######### systematic uncertainty #########

# uncertainty due to different u* threshold

uStarSuffixes <- colnames(REddyProcOutput_ori[["sUSTAR_SCEN"]])[-1]
NEE_suffix_f <- NA
GPP_suffix_f <- NA
RECO_suffix_f <- NA
  
for (i in 1:length(uStarSuffixes)) {
  NEE_suffix_f[i] <- paste0("NEE_", uStarSuffixes[i], "_f" )
  GPP_suffix_f[i] <- paste0("GPP_", uStarSuffixes[i], "_f" )
  RECO_suffix_f[i] <- paste0("Reco_", uStarSuffixes[i])
}

NEE_suffix_f[1] <- "NEE_f"
GPP_suffix_f[1] <- "GPP_f"
RECO_suffix_f[1] <- "Reco"


#--------------- Daily aggregation for systematic uncertainty--------------#

# Compute the mean NEE for each u* threshold 

n_iteration <- 20

compute_sdAggDayUstar <- function(data, type){
  if(type == "NEE") {
    col_suffix <- NEE_suffix_f
  } else if (type == "GPP") {
    col_suffix <- GPP_suffix_f
  } else if (type == "RECO") {
    col_suffix <- RECO_suffix_f
  } else if (type == "RF") {
    col_suffix <- as.character(c(1:n_iteration))
  }
  
  # browser()
  # create NEE, GPP, RECO data
  half_hourly <- data %>% select(date|one_of(col_suffix))
  m_half_hourly <- melt(half_hourly, id.vars = "date") 
  
  # calculate daily NEE, GPP, RECO from the average of each u* scen 
  daily <- dcast(m_half_hourly, date ~ variable, 
                 fun.agg = function(x) mean(x, na.rm = T) * d.avg *co2_conv)
  
  if(type == "RF"){
    sd_daily <- data.frame(daily, SD = rowSds(as.matrix(daily[-1])))
    sd_daily$mean <- rowMeans(sd_daily[-1])
    sd_daily <- sd_daily %>% 
      mutate(upper = mean + SD,  # get mean RF + SD
             lower = mean - SD)  # get mean RF - SD
  } else{
    # calculate the SD of mean NEE, GPP, RECO from across different u* scen
    sd_daily <- data.frame(daily, SD = rowSds(as.matrix(daily[-1]))) %>% 
      mutate(upper = get(col_suffix[1]) + SD,  # get NEE_uStar_f + SD
             lower = get(col_suffix[1]) - SD)  # get NEE_uStar_f - SD
  }
  
  sd_daily
  
  }



###  calculate daily systematic uncertainty from MDS ## 

sdAggDayUstar_NEE <- compute_sdAggDayUstar(REddyProcOutput, "NEE")  # not final, still needs to replace long gaps
sdAggDayUstar_GPP <- compute_sdAggDayUstar(REddyProcOutput, "GPP")  # not final, still needs to replace long gaps
sdAggDayUstar_RECO <- compute_sdAggDayUstar(REddyProcOutput, "RECO")  # this is the final value


######--------- Compute daily SD values from NEE RF gapfilling ------------#########


# define long gaps that will be replaced with SD from RF

long_gaps <- which((sdAggDayUstar_NEE$date >="2015-12-01 00:30:00" &
  sdAggDayUstar_NEE$date < "2016-02-21 00:30:00") | (sdAggDayUstar_NEE$date >= "2016-10-22" &
  sdAggDayUstar_NEE$date < "2017-01-21"))


# compute SD NEE from 20x iteration of RF NEE

result_RF_NEE_wide <- result_RF_NEE %>% 
  pivot_wider(id_cols = DateTime, 
              names_from = iteration,
              values_from = NEE_RF_filled) %>% 
  mutate(DateTime = date(DateTime)) %>% 
  rename(date = DateTime)

sdAggDay_RF_NEE <- compute_sdAggDayUstar(result_RF_NEE_wide, "RF")



######------ replace long gaps values with RF ----------########### 

# replace long gaps in sdAggDayUstar_NEE from MDS with RF result
sdAggDayUstar_NEE_combined <- sdAggDayUstar_NEE
sdAggDayUstar_NEE_combined$NEE_f[long_gaps] <- sdAggDay_RF_NEE$mean[long_gaps]
sdAggDayUstar_NEE_combined$SD[long_gaps] <- sdAggDay_RF_NEE$SD[long_gaps]
sdAggDayUstar_NEE_combined$upper[long_gaps] <- sdAggDay_RF_NEE$upper[long_gaps]
sdAggDayUstar_NEE_combined$lower[long_gaps] <- sdAggDay_RF_NEE$lower[long_gaps]

# we will use RECO as it is, no gaps 

# replace long gaps in sdAggDayUstar_GPP from MDS with NEE-RECO result
sdAggDayUstar_GPP_combined <- sdAggDayUstar_GPP
sdAggDayUstar_GPP_combined$GPP_f[long_gaps] <- sdAggDayUstar_RECO$Reco[long_gaps] - sdAggDay_RF_NEE$mean[long_gaps]
sdAggDayUstar_GPP_combined$SD[long_gaps] <- sqrt(sdAggDayUstar_RECO$SD[long_gaps]^2 + sdAggDay_RF_NEE$SD[long_gaps]^2)
sdAggDayUstar_GPP_combined$upper[long_gaps] <- sdAggDayUstar_GPP_combined$GPP_f[long_gaps] + sdAggDayUstar_GPP_combined$SD[long_gaps]
sdAggDayUstar_GPP_combined$lower[long_gaps] <- sdAggDayUstar_GPP_combined$GPP_f[long_gaps] - sdAggDayUstar_GPP_combined$SD[long_gaps]


# plot daily u* uncertainty 

plot_uncertainty <- function(data, type) {
  if(type == "NEE") {
    variable <- NEE_suffix_f[1]
  } else if (type == "GPP") {
    variable <- GPP_suffix_f[1]
  } else if (type == "RECO") {
    variable <- RECO_suffix_f[1]
  }
  # browser()
  data %>% 
    # filter(date >= "2016-10-15" & date <= "2017-02-01") %>%
    ggplot(aes(x = date, y = get(variable))) +
      geom_line() +
      geom_ribbon(aes(ymin = lower, ymax = upper), 
                alpha=0.1, 
                linetype="dashed",
                color="grey") +
      labs(x = "year", 
           y = bquote(.(type) ~ '(g C' ~m^-2~ day^-1*')'), 
           colour = "") +
      theme_bw()
}


aggDayUstar_NEE_plot <- (plot_uncertainty(sdAggDayUstar_NEE_combined, "NEE"))
aggDayUstar_GPP_plot <- (plot_uncertainty(sdAggDayUstar_GPP_combined, "GPP"))
aggDayUstar_RECO_plot <- (plot_uncertainty(sdAggDayUstar_RECO, "RECO"))


(aggDayUstar_NEE_plot)
(aggDayUstar_GPP_plot)
(aggDayUstar_RECO_plot)




#--------- annual aggregation for systematic uncertainty ---------#

# Compute the mean NEE for each u* threshold 


aggAnnualUstar <- REddyProcOutput %>% 
  ddply("period", summarize, 
        DateTime = first(sDateTime), 
        NEE_f = mean(NEE_f, na.rm = TRUE)* d.avg * co2_conv * 365.5,
        U05 = mean(NEE_U05_f, na.rm = TRUE)* d.avg * co2_conv * 365.5,
        U50 = mean(NEE_U50_f, na.rm = TRUE)* d.avg * co2_conv * 365.5,
        U95 = mean(NEE_U95_f, na.rm = TRUE)* d.avg * co2_conv * 365.5,
        )

sdAggAnnualUstar <- cbind(aggAnnualUstar$period, transform(aggAnnualUstar[ , c(3:6)], 
                           SD=apply(aggAnnualUstar,1, sd, na.rm = TRUE))) %>% 
                  mutate(
                    date = aggAnnualUstar$DateTime,
                    NEE = NEE_f,
                    NEE_U = NEE_f + SD,
                    NEE_L = NEE_f - SD,
                  )


#--------- GS/NGS aggregation for systematic uncertainty ---------#

# number of obs per season
count <- REddyProcOutput %>%
  dplyr::count(period, season)

# Compute the mean NEE for each u* threshold 
aggGSUstar <- REddyProcOutput %>% 
  ddply(c("period", "season"), summarize, 
        DateTime = first(sDateTime), 
        ustar = mean(NEE_uStar_f, na.rm = TRUE)* d.avg * co2_conv,
        U05 = mean(NEE_U05_f, na.rm = TRUE)* d.avg * co2_conv,
        U50 = mean(NEE_U50_f, na.rm = TRUE)* d.avg * co2_conv,
        U95 = mean(NEE_U95_f, na.rm = TRUE)* d.avg * co2_conv,
        ) %>%
  mutate(day_count = count$n/48,  # n of obs/season divided by 48 obs/day to get n day/season
        ustar = ustar * day_count,
        U05 = U05 * day_count,
        U50 = U50 * day_count,
        U95 = U95 * day_count)

sdAggGSUstar <- cbind(aggGSUstar$period, aggGSUstar$season, transform(aggGSUstar[ , c(4:7)], 
                           SD=apply(aggGSUstar,1, sd, na.rm = TRUE))) %>% 
                  mutate(
                    NEE = ustar,
                    NEE_U = ustar + SD,
                    NEE_L = ustar - SD,
                  )


######### calculation from Marion  

#NEE

MN_aggAnnualUstar <- REddyProcOutput %>% 
  ddply("period", summarize, 
        L.2 = mean(NEE_U05_f, na.rm = TRUE) * d.avg * co2_conv * 365.5,
        U.2 = mean(NEE_U95_f, na.rm = TRUE) * d.avg * co2_conv * 365.5) %>% 
  mutate(std.2 = (U.2 - L.2)/(2 * 1.645), 
         CI95.2 = std.2 * 1.96)




######## joint uncertainty ###########


#---------- daily joint uncertainty -----------#

sdDayNEE <- data.frame(
  date = aggDayRand$date,
  sdRand = aggDayRand$sdNEE,
  sdUstar = sdAggDayUstar_NEE$SD,
  sdComb = sqrt(aggDayRand$sdNEE^2 + sdAggDayUstar_NEE$SD^2) 
) %>% 
  mutate(
    NEE = aggDayRand$NEE,
    NEE_U = aggDayRand$NEE + sdComb,
    NEE_L = aggDayRand$NEE - sdComb,
  )


# Plot daily joint uncertainty 
(sdDayNEE %>% 
  filter(date >= "2020-03-01" & date <= "2020-05-01") %>% 
  ggplot(aes(x = date, y = NEE)) +
    geom_line() +
    geom_ribbon(aes(ymin = NEE_L, ymax = NEE_U), 
              alpha=0.1, 
              linetype="dashed",
              color="grey") +
    labs(x = "year", 
         y = bquote('NEE (g C' ~m^-2~ day^-1*')'), 
         colour = "") +
    theme_bw())


#---------- annual joint uncertainty -----------#

sdAnnualNEE <- data.frame(
  period = aggAnnualRand$period,
  sdRand = aggAnnualRand$sdNEE,
  sdUstar = sdAggAnnualUstar$SD,
  sdComb = sqrt(aggAnnualRand$sdNEE^2 + sdAggAnnualUstar$SD^2) 
) %>% 
  mutate(
    NEE = aggAnnualRand$NEE,
    NEE_U = aggAnnualRand$NEE + sdComb,
    NEE_L = aggAnnualRand$NEE - sdComb,
  )

```

```{r cumsum uncertainty for NEE}



######################### Cumulative random uncertainty #############################

aggDayRand_cum <- REddyProcOutput %>% 
  group_by(period, isna = is.na(NEE_f)) %>% 
  mutate(t = (seq(1, length(sDateTime), by = 1)) * 30 * 60) %>%  # create cumulative timestep
  mutate(DateTime = date(sDateTime),
         n_NEE_fqc = ifelse(NEE_fqc != 0 |is.na(NEE_fqc), 0, 1),
         nRec = cumsum(n_NEE_fqc == 1), 
         NEE = ifelse(isna, NA, cummean(NEE_f) * co2_conv * t),
         sdNEE = ifelse(isna, NA, cummean(NEE_fsd^2))
  ) %>% 
  group_by(date) %>% 
  filter(sDateTime == max(sDateTime)) %>%  # pick the last time of each day to get daily cumulative
  ungroup() %>%
  mutate(nEff = aggDayRand$nEff) %>%  # get nEff from the daily random uncertainty table
  group_by(period) %>% 
  mutate(nEff = cumsum(nEff))%>%  # calculate cumulative daily nEff 
  ungroup() %>%
  mutate(sdNEE = if(nEff <= 1)
            NA_real_
          else ifelse(isna, NA, sqrt(sdNEE / (nEff - 1)  * co2_conv * t)),
          sdNEEuncorr = if(nRec == 0)
            NA_real_
          else ifelse(isna, NA, sqrt(sdNEE / (nRec - 1) * co2_conv * t))
  ) %>%
  mutate(sdNEE = sdNEE,
         NEE = NEE) %>% 
  mutate( 
    NEE_U = NEE + sdNEE, 
    NEE_L = NEE - sdNEE) %>% 
  select(colnames(aggDayRand))


# check plot 

(aggDayRand %>% 
    mutate(cumsum = cumsum(NEE)) %>%
  filter(date >= "2015-07-01" & date <= "2015-08-20") %>%
  ggplot(aes(x = date, y = cumsum)) +
    geom_line() +
    theme_bw())

# check cumulative random uncertainty plot
(aggDayRand_cum %>% 
  filter(date >= "2015-07-01" & date <= "2015-08-20") %>%
  ggplot(aes(x = date, y = NEE)) +
    geom_line() +
    geom_ribbon(aes(ymin = NEE_L, ymax = NEE_U), 
              alpha=0.1, 
              linetype="dashed",
              color="grey") +
    labs(x = "year", 
         y = bquote('NEE (g C' ~m^-2~ day^-1*')'), 
         colour = "") +
    theme_bw())




################## cumulative systematic uncertainty ####################


sdAggDayUstar_NEE_combined <- set_period(sdAggDayUstar_NEE_combined)


sdAggDayUstar_NEE_combined$month_local <- month(sdAggDayUstar_NEE_combined$date)

# set season 
GS <- sdAggDayUstar_NEE_combined$month_local %in% c(4, 5, 6, 7, 8, 9)
NGS <- sdAggDayUstar_NEE_combined$month_local %in% c(10, 11, 12, 1, 2, 3)
sdAggDayUstar_NEE_combined$season[GS] <- "growing season"
sdAggDayUstar_NEE_combined$season[NGS] <- "non-growing season"


long_gaps <- which((sdAggDayUstar_NEE_combined$date >="2015-12-01 00:30:00" &
  sdAggDayUstar_NEE_combined$date < "2016-02-21 00:30:00") | 
  (sdAggDayUstar_NEE_combined$date >= "2016-10-22" &
  sdAggDayUstar_NEE_combined$date < "2017-01-21"))



calculate_cumsum_unc <- function(data, ind, variable, start_mean, start_SD){  #variable = "NEE_f" or "mean"; ind = iter_ind or ustar_ind; data = NEE_method_cumsum

  # if start_point is new; use the first row value; if start_point is previous, use result from previous cumsum period to add to the first row
  data[1, ind] <- data[1, ind] + start_mean
  
  # calculate cumsum 
  data[ , ind] <- cumsum(data[ , ind])

  # for random forest, the flux value is calculated from the mean
  if(variable == "mean"){
      data[ , "mean"] <- rowMeans(data[ , ind])
  } else{
      data[, "mean"] <- data[, variable]
  }
  

  # calculate SD
  data[ , "SD_ori"] <- rowSds(as.matrix(data[ , ind]))
  
  # if start point is new, use SD as it is; if start point of SD is from the previous, sqrt(prev_SD^2 + current_SD^2)
  data[, "SD"] <- sqrt(data[ , "SD_ori"]^2 + start_SD^2)
  
  # data[ , "upper"] <- data[, variable] + data$SD
  # data[ , "lower"] <- data[, variable] - data$SD
  end_mean <- data[nrow(data), "mean"]
  end_SD <- data[nrow(data), "SD"]

  list(cumsum = data,
       end_mean = end_mean,
       end_SD = end_SD)
}



############---------- 2015-2016 period -------------############

# y_2015_2016 <- =date >= "2015-06-20" & date < "2016-06-20"

## MDS 1
NEE_MDS1_cumsum <- sdAggDayUstar_NEE_combined %>% filter(period == "2015-2016" & date <"2015-12-01") 
ustar_ind <- grep("NEE_", colnames(NEE_MDS1_cumsum), value = T)
NEE_MDS1_cumsum <- calculate_cumsum_unc(data = NEE_MDS1_cumsum,
                             ind = ustar_ind, 
                             variable = "NEE_f", 
                             start_mean = 0, 
                             start_SD = 0)

## long gaps RF1
NEE_RF1_cumsum <- sdAggDay_RF_NEE %>% filter(date >="2015-12-01 00:30:00" & date < "2016-02-21 00:30:00")
iter_ind <- grep("X", colnames(NEE_RF1_cumsum), value = T)
NEE_RF1_cumsum <- calculate_cumsum_unc(data = NEE_RF1_cumsum,
                             ind = iter_ind, 
                             variable = "mean", 
                             start_mean = NEE_MDS1_cumsum[[2]], 
                             start_SD = NEE_MDS1_cumsum[[3]])

## MDS 2
NEE_MDS2_cumsum <- sdAggDayUstar_NEE_combined %>% 
  filter(date >= "2016-02-21 00:30:00" & date <"2016-10-01 00:30:00") %>%
  calculate_cumsum_unc(data = .,
                             ind = ustar_ind, 
                             variable = "NEE_f", 
                             start_mean = NEE_RF1_cumsum[[2]], 
                             start_SD = NEE_RF1_cumsum[[3]])

## combine MDS and RF
NEE_cumsum_2015_2016 <- smartbind(NEE_MDS1_cumsum[[1]], NEE_RF1_cumsum[[1]], NEE_MDS2_cumsum[[1]]) %>% 
  select("date", "SD", "mean") %>% 
  mutate(upper = mean + SD, 
         lower = mean - SD, 
         period = "2015-2016", 
         date = date(date))


(NEE_cumsum_2015_2016 %>% 
  ggplot(aes(x = date(date), y = mean)) +
    geom_line() +
    geom_ribbon(aes(ymin = lower, ymax = upper), 
              alpha=0.1, 
              linetype="dashed",
              color="grey") +
    labs(x = "year", 
         y = bquote('NEE (g C' ~m^-2~ day^-1*')'), 
         colour = "") +
    theme_bw())


############---------- 2016-2017 period -------------############


## MDS 3
NEE_MDS3_cumsum <- sdAggDayUstar_NEE_combined %>% 
  filter(date >= "2016-10-01 00:30:00" & date < "2016-10-22 00:30:00") %>%
  calculate_cumsum_unc(data = .,
                             ind = ustar_ind, 
                             variable = "NEE_f", 
                             start_mean = 0, 
                             start_SD = 0)

## long gap RF2
NEE_RF2_cumsum <- sdAggDay_RF_NEE %>% 
  filter(date >= "2016-10-22 00:30:00" & date < "2017-01-21 00:30:00")%>% 
  calculate_cumsum_unc(data = .,
                             ind = iter_ind, 
                             variable = "mean", 
                             start_mean = NEE_MDS3_cumsum[[2]], 
                             start_SD = NEE_MDS3_cumsum[[3]])

## MDS4
NEE_MDS4_cumsum <- sdAggDayUstar_NEE_combined %>% 
  filter(date >= "2017-01-21 00:30:00" & date < "2017-10-01 00:30:00") %>% 
  calculate_cumsum_unc(data = .,
                             ind = ustar_ind, 
                             variable = "NEE_f", 
                             start_mean = NEE_RF2_cumsum[[2]], 
                             start_SD = NEE_RF2_cumsum[[3]])

## Combine MDS & RF
NEE_cumsum_2016_2017 <- smartbind(NEE_MDS3_cumsum[[1]], NEE_RF2_cumsum[[1]], NEE_MDS4_cumsum[[1]]) %>% 
  select("date", "SD", "mean") %>% 
  mutate(upper = mean + SD, 
         lower = mean - SD, 
         period = "2016-2017", 
         date = date(date))

(NEE_cumsum_2016_2017 %>% 
  ggplot(aes(x = date(date), y = mean)) +
    geom_line() +
    geom_ribbon(aes(ymin = lower, ymax = upper), 
              alpha=0.1, 
              linetype="dashed",
              color="grey") +
    labs(x = "year", 
         y = bquote('NEE (g C' ~m^-2~ day^-1*')'), 
         colour = "") +
    theme_bw())


############---------- 2017-2021 period -------------############

## set period
period <- unique(sdAggDayUstar_NEE_combined$period)[3:6]


cumsum_i <- NA
NEE_cumsum_2017_2021 <- NA
for(i in period){
  cumsum_i <- sdAggDayUstar_NEE_combined %>% filter(period == i) 
  cumsum_i <- calculate_cumsum_unc(data = cumsum_i, 
                                 ind = ustar_ind, 
                                 variable = "NEE_f", 
                                 start_mean = 0, 
                                 start_SD = 0)
  cumsum_i <- cumsum_i[[1]] %>% 
    select("date", "SD", "mean") %>% 
    mutate(upper = mean + SD, 
           lower = mean - SD, 
           period = i)
  if(i == "2017-2018") {
    NEE_cumsum_2017_2021 <- cumsum_i
  } else {
    NEE_cumsum_2017_2021 <- rbind(NEE_cumsum_2017_2021, cumsum_i)
  }
}

  
NEE_ustar_cumsum <- rbind(NEE_cumsum_2015_2016, NEE_cumsum_2016_2017, NEE_cumsum_2017_2021) %>% 
  group_by(period) %>%
  arrange(date) %>%
  mutate(order = row_number()) %>% 
  ungroup() %>%
  mutate(day_label = case_when(day(date) == 1L ~ format(date, "%b"),
                     TRUE ~ NA_character_)
         )

#############----------- ggplot ---------###########

# set x axis
x_break <- NEE_ustar_cumsum$order[!is.na(NEE_ustar_cumsum$day_label)][1:12]
x_label <- NEE_ustar_cumsum$day_label[!is.na(NEE_ustar_cumsum$day_label)][1:12]

(NEE_ustar_cumsum %>% 
  ggplot(aes(x = order, y = mean, color = factor(period), group = factor(period))) +
    geom_line(size = 1) +
    geom_ribbon(aes(ymin = lower, ymax = upper), 
              alpha=0.1, 
              linetype="dashed",
              fill = "grey") +
    labs(x = "Month", 
         y = bquote('NEE (g C' ~m^-2~ day^-1*')'), 
         colour = "") +
    theme_bw())

NEE_ustar_cumsum_annual <- NEE_ustar_cumsum %>% 
  group_by(period) %>% 
  filter(date == max(date)) %>%  # pick the last time of each day to get daily cumulative
  ungroup()



#####------------- combine cumulative random and u* uncertainty -------------###

aggUnc_NEE_cumsum <- left_join(NEE_ustar_cumsum, filter(aggDayRand_cum, date < "2021-06-20")) %>% 
  select(date, SD, mean, period, order, day_label, sdNEE) 

aggUnc_NEE_cumsum$sdNEE[is.na(aggUnc_NEE_cumsum$sdNEE)] <- 0

aggUnc_NEE_cumsum <- aggUnc_NEE_cumsum %>% 
  mutate(joint_sd = sqrt(SD^2 + sdNEE^2), 
         joint_CI = joint_sd * 1.96,
         upper = mean + joint_CI, 
         lower = mean - joint_CI)

NEE_cumsum_plot <- aggUnc_NEE_cumsum %>% 
  ggplot(aes(x = order, y = mean, color = factor(period), group = factor(period))) +
    geom_line(size = 1) +
    geom_ribbon(aes(ymin = lower, ymax = upper, 
                    fill = period, linetype = NA), 
              alpha=0.15) +
    scale_x_continuous(breaks = unique(x_break),
                       labels = unique(x_label)) +
    labs(x = "Month",  
         y = bquote('NEE (g C' ~m^-2~ day^-1*')'), 
         colour = "", 
         fill = "") +
    theme_bw()


NEE_joint_cumsum_annual <- aggUnc_NEE_cumsum %>% 
  group_by(period) %>% 
  filter(date == max(date)) %>%  # pick the last time of each day to get daily cumulative
  ungroup()


```

```{r cumsum uncertainty for RECO}


sdAggDayUstar_RECO <- set_period(sdAggDayUstar_RECO)

ustar_ind <- grep("Reco", colnames(sdAggDayUstar_RECO), value = T)

period <- unique(sdAggDayUstar_RECO$period) 
period <- period[!is.na(period)]

cumsum_i <- NA
Reco_cumsum_2015_2021 <- NA

for(i in period){
  cumsum_i <- sdAggDayUstar_RECO %>% filter(period == i) 
  cumsum_i <- calculate_cumsum_unc(data = cumsum_i, 
                                 ind = ustar_ind, 
                                 variable = "Reco", 
                                 start_mean = 0, 
                                 start_SD = 0)
  cumsum_i <- cumsum_i[[1]] %>% 
    select("date", "SD", "mean") %>% 
    mutate(CI = SD * 1.96, 
           upper = mean + CI, 
           lower = mean - CI, 
           period = i)
  if(i == "2015-2016") {
    Reco_cumsum_2015_2021 <- cumsum_i
  } else {
    Reco_cumsum_2015_2021 <- rbind(Reco_cumsum_2015_2021, cumsum_i)
  }
}

  
Reco_ustar_cumsum <- Reco_cumsum_2015_2021 %>% 
  group_by(period) %>%
  arrange(date) %>%
  mutate(order = row_number()) %>% 
  ungroup() %>%
  mutate(day_label = case_when(day(date) == 1L ~ format(date, "%b"),
                     TRUE ~ NA_character_)
         )

#############----------- ggplot ---------###########


x_break <- Reco_ustar_cumsum$order[!is.na(Reco_ustar_cumsum$day_label)][1:12]
x_label <- Reco_ustar_cumsum$day_label[!is.na(Reco_ustar_cumsum$day_label)][1:12]

Reco_cumsum_plot <- Reco_ustar_cumsum %>% 
  ggplot(aes(x = order, y = mean, color = factor(period), group = factor(period))) +
    geom_line(size = 1) +
    geom_ribbon(aes(ymin = lower, ymax = upper, 
              linetype=NA, fill = period), 
              alpha=0.15) +
    scale_x_continuous(breaks = unique(x_break),
                       labels = unique(x_label)) +
    labs(x = "Month", 
         y = bquote('Reco (g C' ~m^-2~ day^-1*')'), 
         colour = "", 
         fill = "") +
    theme_bw()

Reco_ustar_cumsum_annual <- Reco_ustar_cumsum %>% 
  group_by(period) %>% 
  filter(date == max(date)) %>%  # pick the last time of each day to get daily cumulative
  ungroup()
```

```{r cumsum uncertainty for GPP}

# AAAAAAAAAAAAAAAAA

############---------- 2015-2016 period -------------############

### MDS
GPP_MDS1_cumsum <- sdAggDayUstar_GPP %>% filter(period == "2015-2016" & date <"2015-12-01") 
ustar_ind <- grep("GPP_", colnames(GPP_MDS1_cumsum), value = T)
GPP_MDS1_cumsum <- calculate_cumsum_unc(data = GPP_MDS1_cumsum,
                             ind = ustar_ind, 
                             variable = "GPP_f", 
                             start_mean = 0, 
                             start_SD = 0)

### long gap RF

# calculate SD RF NEE
iter_ind <- grep("X", colnames(sdAggDay_RF_NEE), value = T)
GPP_RF1_cumsum_NEE <- sdAggDay_RF_NEE %>% 
  filter(date >="2015-12-01 00:30:00" & date < "2016-02-21 00:30:00") %>% 
  calculate_cumsum_unc(data = .,
                       ind = iter_ind, 
                       variable = "mean", 
                       start_mean = 0, 
                       start_SD = 0)
ustar_ind <- grep("Reco", colnames(sdAggDayUstar_RECO), value = T)

# calculate SD MDS Reco
GPP_RF1_cumsum_RECO <- sdAggDayUstar_RECO %>% 
  filter(date >="2015-12-01 00:30:00" & date < "2016-02-21 00:30:00") %>% 
  calculate_cumsum_unc(data = .,
                       ind = ustar_ind, 
                       variable = "Reco", 
                       start_mean = 0, 
                       start_SD = 0)

# calculate SD GPP from Reco & NEE
GPP_RF1_cumsum <- data.frame(date = GPP_RF1_cumsum_NEE$cumsum$date, 
                             mean = GPP_MDS1_cumsum[[2]] + (GPP_RF1_cumsum_RECO$cumsum$mean - GPP_RF1_cumsum_NEE$cumsum$mean), 
                             SD = sqrt((GPP_RF1_cumsum_RECO$cumsum$SD^2) + 
                                        (GPP_RF1_cumsum_NEE$cumsum$SD^2 + 
                                        GPP_MDS1_cumsum[[3]]^2)))

### MDS 2 
ustar_ind <- grep("GPP", colnames(sdAggDayUstar_GPP), value = T)
GPP_MDS2_cumsum <- sdAggDayUstar_GPP %>% 
  filter(date >= "2016-02-21 00:30:00" & date <"2016-10-01 00:30:00") %>%
  calculate_cumsum_unc(data = .,
                             ind = ustar_ind, 
                             variable = "GPP_f", 
                             start_mean = GPP_RF1_cumsum[nrow(GPP_RF1_cumsum), "mean"], 
                             start_SD = GPP_RF1_cumsum[nrow(GPP_RF1_cumsum), "SD"])


# combine
GPP_cumsum_2015_2016 <- smartbind(select(GPP_MDS1_cumsum[[1]], c("date", "SD", "mean")),
                                  GPP_RF1_cumsum, 
                                  select(GPP_MDS2_cumsum[[1]], c("date", "SD", "mean"))) %>% 
  mutate(upper = mean + SD, 
         lower = mean - SD, 
         period = "2015-2016", 
         date = date(date))


(GPP_cumsum_2015_2016 %>% 
  ggplot(aes(x = date(date), y = mean)) +
    geom_line() +
    geom_ribbon(aes(ymin = lower, ymax = upper), 
              alpha=0.15, 
              linetype="dashed",
              color="grey") +
    labs(x = "year", 
         y = bquote('GPP (g C' ~m^-2~ day^-1*')'), 
         colour = "") +
    theme_bw())


############---------- 2016-2017 period -------------############

## not done


### MDS 3
GPP_MDS3_cumsum <- sdAggDayUstar_GPP %>% 
  filter(date >= "2016-10-01 00:30:00" & date < "2016-10-22 00:30:00") %>% 
  calculate_cumsum_unc(data = .,
                             ind = ustar_ind, 
                             variable = "GPP_f", 
                             start_mean = 0, 
                             start_SD = 0)

### long gap RF

# calculate SD RF NEE
iter_ind <- grep("X", colnames(sdAggDay_RF_NEE), value = T)
GPP_RF2_cumsum_NEE <- sdAggDay_RF_NEE %>% 
  filter(date >= "2016-10-22 00:30:00" & date < "2017-01-21 00:30:00")%>% 
  calculate_cumsum_unc(data = .,
                       ind = iter_ind, 
                       variable = "mean", 
                       start_mean = 0, 
                       start_SD = 0)
ustar_ind <- grep("Reco", colnames(sdAggDayUstar_RECO), value = T)

# calculate SD MDS Reco
GPP_RF2_cumsum_RECO <- sdAggDayUstar_RECO %>% 
  filter(date >= "2016-10-22 00:30:00" & date < "2017-01-21 00:30:00")%>% 
  calculate_cumsum_unc(data = .,
                       ind = ustar_ind, 
                       variable = "Reco", 
                       start_mean = 0, 
                       start_SD = 0)

# calculate SD GPP from Reco & NEE
GPP_RF2_cumsum <- data.frame(date = GPP_RF2_cumsum_NEE$cumsum$date, 
                             mean = GPP_MDS3_cumsum[[2]] + (GPP_RF2_cumsum_RECO$cumsum$mean - GPP_RF2_cumsum_NEE$cumsum$mean), 
                             SD = sqrt((GPP_RF2_cumsum_RECO$cumsum$SD^2) + 
                                        (GPP_RF2_cumsum_NEE$cumsum$SD^2 + 
                                        GPP_MDS3_cumsum[[3]]^2)))

### MDS 4 
ustar_ind <- grep("GPP", colnames(sdAggDayUstar_GPP), value = T)
GPP_MDS4_cumsum <- sdAggDayUstar_GPP %>% 
  filter(date >= "2017-01-21 00:30:00" & date < "2017-10-01 00:30:00") %>% 
  calculate_cumsum_unc(data = .,
                       ind = ustar_ind, 
                       variable = "GPP_f", 
                       start_mean = GPP_RF2_cumsum[nrow(GPP_RF2_cumsum), "mean"], 
                       start_SD = GPP_RF2_cumsum[nrow(GPP_RF2_cumsum), "SD"])


# combine
GPP_cumsum_2016_2017 <- smartbind(select(GPP_MDS3_cumsum[[1]], c("date", "SD", "mean")),
                                  GPP_RF2_cumsum, 
                                  select(GPP_MDS4_cumsum[[1]], c("date", "SD", "mean"))) %>% 
  mutate(upper = mean + SD, 
         lower = mean - SD, 
         period = "2016-2017", 
         date = date(date))


(GPP_cumsum_2016_2017 %>% 
  ggplot(aes(x = date(date), y = mean)) +
    geom_line() +
    geom_ribbon(aes(ymin = lower, ymax = upper), 
              alpha=0.1, 
              linetype="dashed",
              color="grey") +
    labs(x = "year", 
         y = bquote('GPP (g C' ~m^-2~ day^-1*')'), 
         colour = "") +
    theme_bw())



############---------- 2017-2021 period -------------############


sdAggDayUstar_GPP <- set_period(sdAggDayUstar_GPP)

period <- unique(sdAggDayUstar_GPP$period)[3:6]

cumsum_i <- NA
GPP_cumsum_2017_2021 <- NA
for(i in period){
  cumsum_i <- sdAggDayUstar_GPP %>% filter(period == i) 
  cumsum_i <- calculate_cumsum_unc(data = cumsum_i, 
                                 ind = ustar_ind, 
                                 variable = "GPP_f", 
                                 start_mean = 0, 
                                 start_SD = 0)
  cumsum_i <- cumsum_i[[1]] %>% 
    select("date", "SD", "mean") %>% 
    mutate(upper = mean + SD, 
           lower = mean - SD, 
           period = i)
  if(i == "2017-2018") {
    GPP_cumsum_2017_2021 <- cumsum_i
  } else {
    GPP_cumsum_2017_2021 <- rbind(GPP_cumsum_2017_2021, cumsum_i)
  }
}

  
GPP_ustar_cumsum <- rbind(GPP_cumsum_2015_2016, GPP_cumsum_2016_2017, GPP_cumsum_2017_2021) %>% 
  group_by(period) %>%
  arrange(date) %>%
  mutate(order = row_number()) %>% 
  ungroup() %>%
  mutate(day_label = case_when(day(date) == 1L ~ format(date, "%b"),
                     TRUE ~ NA_character_), 
         CI = SD * 1.96, 
         upper = mean + CI, 
         lower = mean - CI)

#############----------- ggplot ---------###########


x_break <- GPP_ustar_cumsum$order[!is.na(GPP_ustar_cumsum$day_label)][1:12]
x_label <- GPP_ustar_cumsum$day_label[!is.na(GPP_ustar_cumsum$day_label)][1:12]

GPP_cumsum_plot <- GPP_ustar_cumsum %>% 
  ggplot(aes(x = order, y = mean, color = factor(period), group = factor(period))) +
    geom_line(size = 1) +
    geom_ribbon(aes(ymin = lower, ymax = upper, 
                    fill = period, linetype = NA), 
              alpha=0.15) +
    scale_x_continuous(breaks = x_break,
                       labels = x_label) +
    labs(x = "Month", 
         y = bquote('GPP (g C' ~m^-2~ day^-1*')'), 
         color = "", 
         fill = "") +
    theme_bw()

GPP_ustar_cumsum_annual <- GPP_ustar_cumsum %>% 
  group_by(period) %>% 
  filter(date == max(date)) %>%  # pick the last time of each day to get daily cumulative
  ungroup()



```

```{r cumsum uncertainty for CH4}

# compute SD NEE from 20x iteration of RF NEE

result_RF_FCH4_wide <- result_RF_FCH4 %>% 
  pivot_wider(id_cols = DateTime, 
              names_from = iteration,
              values_from = FCH4_RF_filled) %>% 
  mutate(DateTime = date(DateTime)) %>% 
  rename(date = DateTime)

sdAggDay_RF_FCH4 <- compute_sdAggDayUstar(result_RF_FCH4_wide, "RF") %>% 
  set_period(.)

period <- unique(sdAggDay_RF_FCH4$period)
period <- period[which(!is.na(period))]
iter_ind <- grep("X", colnames(sdAggDay_RF_FCH4), value = T)

cumsum_i <- NA
FCH4_cumsum_2015_2021 <- NA
for(i in period){
  cumsum_i <- sdAggDay_RF_FCH4 %>% filter(period == i) 
  cumsum_i <- calculate_cumsum_unc(data = cumsum_i, 
                                 ind = iter_ind, 
                                 variable = "mean", 
                                 start_mean = 0, 
                                 start_SD = 0)
  cumsum_i <- cumsum_i[[1]] %>% 
    select("date", "SD", "mean") %>% 
    mutate(CI = SD * 1.96,
           upper = mean + CI, 
           lower = mean - CI, 
           period = i)
  if(i == "2015-2016") {
    FCH4_cumsum_2015_2021 <- cumsum_i
  } else {
    FCH4_cumsum_2015_2021 <- rbind(FCH4_cumsum_2015_2021, cumsum_i)
  }
}

  
FCH4_unc_cumsum <- FCH4_cumsum_2015_2021 %>% 
  group_by(period) %>%
  arrange(date) %>%
  mutate(order = row_number()) %>% 
  ungroup() %>%
  mutate(day_label = case_when(day(date) == 1L ~ format(date, "%b"),
                     TRUE ~ NA_character_)
         )

#############----------- ggplot ---------###########


x_break <- FCH4_unc_cumsum$order[!is.na(FCH4_unc_cumsum$day_label)][1:12]
x_label <- FCH4_unc_cumsum$day_label[!is.na(FCH4_unc_cumsum$day_label)][1:12]

FCH4_cumsum_plot <- FCH4_unc_cumsum %>% 
  ggplot(aes(x = order, y = mean, color = factor(period), group = factor(period))) +
    geom_line(size = 1) +
    geom_ribbon(aes(ymin = lower, ymax = upper, 
                    linetype = NA, fill = period), 
              alpha=0.1) +
    scale_x_continuous(breaks = unique(x_break),
                       labels = unique(x_label)) +
    labs(x = "Month", 
         y = bquote('FCH4 (g C' ~m^-2~ day^-1*')'), 
         colour = "", 
         fill = "") +
    theme_bw()

FCH4_unc_cumsum_annual <- FCH4_unc_cumsum %>% 
  group_by(period) %>% 
  filter(date == max(date)) %>%  # pick the last time of each day to get daily cumulative
  ungroup()


```

```{r save plots and docs}

print(NEE_cumsum_plot)
ggsave("plots/NEE_cumsum_plot.png")
print(GPP_cumsum_plot)
ggsave("plots/GPP_cumsum_plot.png")
print(Reco_cumsum_plot)
ggsave("plots/Reco_cumsum_plot.png")
print(FCH4_cumsum_plot)
ggsave("plots/FCH4_cumsum_plot.png")


# save calculations 
daily_unc <- data.frame(date = aggUnc_NEE_cumsum$date, 
                        NEE = aggUnc_NEE_cumsum$mean, 
                        NEE_CI = aggUnc_NEE_cumsum$joint_CI, 
                        GPP = GPP_ustar_cumsum$mean, 
                        GPP_CI = GPP_ustar_cumsum$CI, 
                        RECO = Reco_ustar_cumsum$mean, 
                        RECO_CI = Reco_ustar_cumsum$CI)
write.csv(daily_unc, paste0(here::here(), "/df/daily_filled_NEE.csv"))

```


```{r C and GHG budget} 


# calculate net C and GHG budgets along with their uncertainties
annual_budget <- data.frame(
                     date = NEE_joint_cumsum_annual$date, 
                     period = NEE_joint_cumsum_annual$period,
                     NEEgC_f_RF = NEE_joint_cumsum_annual$mean,
                     NEEgC_f_RF_CI = NEE_joint_cumsum_annual$joint_CI, 
                     GPPgC_f_RF = GPP_ustar_cumsum_annual$mean, 
                     GPPgC_f_RF_CI = GPP_ustar_cumsum_annual$CI, 
                     RecogC = Reco_ustar_cumsum_annual$mean, 
                     RecogC_CI = Reco_ustar_cumsum_annual$CI, 
                     CH4gC_f_RF = FCH4_unc_cumsum_annual$mean, 
                     CH4gC_f_RF_CI = FCH4_unc_cumsum_annual$CI
                     ) %>% 
  mutate(net_C_budget = NEEgC_f_RF + CH4gC_f_RF, 
         net_C_budget_CI = sqrt(NEEgC_f_RF_CI^2 + CH4gC_f_RF_CI^2), 
         CO2_seq = (NEEgC_f_RF + CH4gC_f_RF) * 44.01 / 12.01,  # in g CO2
         CO2_seq_CI = sqrt(NEEgC_f_RF_CI^2 + CH4gC_f_RF_CI^2) * 44.01 / 12.01,
         GHG_SGWP_20 = CO2_seq + (CH4gC_f_RF * 16.04 / 12.01 * 96),  # in g CO2-eq, using 20y SGWP = 96
         GHG_SGWP_20_CI = sqrt(CO2_seq_CI^2 + (CH4gC_f_RF_CI * 16.04 / 12.01 * 96)^2),
         GHG_SGWP_100 = CO2_seq + (CH4gC_f_RF * 16.04 / 12.01 * 45),  # in g CO2-eq, using 100y SGWP = 45
         GHG_SGWP_100_CI =  sqrt(CO2_seq_CI^2 + (CH4gC_f_RF_CI * 16.04 / 12.01 * 45)^2),
         GHG_GWP_20 = (NEEgC_f_RF * 44.01 / 12.01) + (CH4gC_f_RF * 16.04 / 12.01 * 84),  # in g CO2-eq, using 20y SGWP = 84, 
         GHG_GWP_20_CI = sqrt((NEEgC_f_RF_CI* 44.01 / 12.01)^2 + (CH4gC_f_RF_CI * 16.04 / 12.01 * 84)^2),
         GHG_GWP_100 = (NEEgC_f_RF * 44.01 / 12.01) + (CH4gC_f_RF * 16.04 / 12.01 * 28),  # in g CO2-eq, , using 100y SGWP = 28
         GHG_GWP_100_CI = sqrt((NEEgC_f_RF_CI* 44.01 / 12.01)^2 + (CH4gC_f_RF_CI * 16.04 / 12.01 * 28)^2), 
  )

write.csv(annual_budget, paste0(here::here(), "/df/annual_budget.csv"))


# calculate seasonal net C budget






```





# Daily plots 

## Non gap-filled $CO_2$ & $CH_4$ Fluxes 

**Non gap-filled** $CO_2$ & $CH_4$ fluxes. daily fluxes are calculated only from days with at least 60% half-hourly data available. 

```{r, message = F, warning = F}
co2_ngf <- plot_daily(data = daily.nGF, 
                   variable = co2gC, 
                   label = expression("CO"[2]*" flux (gC"*m^{-2}~day^{-1}*")"), 
                   ma = 1
                   )
ch4_ngf <- plot_daily(data = daily.nGF, 
                   variable = ch4gC, 
                   label = expression("CH"[4]*" flux (gC"*m^{-2}~day^{-1}*")"), 
                   ma = 1
                   )
(co2_ngf)
(ch4_ngf)

```

## Gap-filled daily $CO_2$ & $CH_4$ fluxes

```{r, message = F, warning = F}
RecogC <- plot_daily(data = daily, 
                   variable = RecogC, 
                   label = bquote('Reco (g C' ~m^-2~ day^-1*')'), 
                   ma = 1)
GPPgC_f <- plot_daily(data = daily, 
                   variable = GPPgC_f, 
                   label = bquote('GPP (g C' ~m^-2~ day^-1*')'), 
                   ma = 1)
GPPgC_f_RF <- plot_daily(data = daily, 
                   variable = GPPgC_f_RF, 
                   label = bquote('GPP RF(g C' ~m^-2~ day^-1*')'), 
                   ma = 1) 
NEEgC_f <- plot_daily(data = daily, 
                   variable = NEEgC_f, 
                   label = bquote('NEE (g C' ~m^-2~ day^-1*')'), 
                   ma = 1) 
NEEgC_f_RF <- plot_daily(data = daily, 
                   variable = NEEgC_f_RF, 
                   label = bquote('NEE RF(g C' ~m^-2~ day^-1*')'), 
                   ma = 1) 
CH4gC_f <- plot_daily(data = daily, 
                   variable = CH4gC_f, 
                   label = bquote('CH4 (g C' ~m^-2~ day^-1*')'), 
                   ma = 1)
CH4gC_f_RF <- plot_daily(data = daily, 
                   variable = CH4gC_f_RF, 
                   label = bquote('CH4 flux - random forest (g C' ~m^-2~ day^-1*')'), 
                   ma = 1)
(NEEgC_f)
(GPPgC_f)
(RecogC)
(CH4gC_f_RF)
(NEEgC_f_RF)
(GPPgC_f_RF)


GPP_comparison <- daily %>% 
  ggplot() +
    geom_line(aes(x = date, y = GPPgC_f_RF, col = "RF")) +
    geom_line(aes(x = date, y = GPP_f, col = "MDS")) +
    scale_color_manual(values = c("RF" = "blue", 
                                  "MDS" = "black")) +
    labs(x = "year", 
         y = "GPP (gC m-2 day-1)", 
         colour = "")  + 
  theme_bw()

NEE_comparison <- daily %>%
  ggplot() +
    # geom_line(aes(x = date, y = co2gC, col = "nGF"), data = daily.nGF) +
    geom_line(aes(x = date, y = NEEgC_f_RF, col = "RF"), data = daily) +
    geom_line(aes(x = date, y = NEE_f, col = "MDS"), data = daily) +
    scale_color_manual(values = c("RF" = "blue", 
                                  # "nGF" = "blue",
                                  "MDS" = "black")) +
    labs(x = "year", 
         y = "NEE (gC m-2 day-1)", 
         colour = "") +
    theme_bw()

ggplotly(NEE_comparison)
ggplotly(GPP_comparison)

```


## Meteorological variables 

```{r Data wrangling for met variables, include = F, message = F, warning = F}

BB_met <- BB1 %>%  
  rename("TS.5" = "SOIL_TEMP_5CM", 
         "TS.10" = "SOIL_TEMP_10CM",
         "TS.50" = "SOIL_TEMP_50CM") %>% 
  group_by(date) %>% 
  summarize(
      TS.5 = mean(TS.5),  # soil temp
      TS.10 = mean(TS.10),
      TS.50 = mean(TS.50),
      RH = mean(RH_2M),  # relative humidity
      PARin = mean(INCOMING_PAR) * d.avg * 1e-6,  # mol m2 day -1 
      SWin = mean(SHORTWAVE_IN),
      VPD.y = mean(VPD.y),
      VPD.x = mean(VPD.x),
      Precip = sum(PRECIP),
      PA_EC = mean(PA_EC2_AIR),  # barrometric pressure from EC
      PA_2M = mean(PA_2M),  # barrometric pressure from met
      Ta = mean(AIR_TEMP_2M),  # air temp at 2 m
      # WTH2 = mean(4.606 -(-0.89*WTH2+82)/100),  # water table height before 2018
      wtd = mean(WTH_absolute),  # water Marion
      SWC = mean(SVWC) # soil water content
      ) %>%  
  mutate(month_local = month(date), 
         year_local = year(date), 
         floor_date = floor_date(date, "month"))%>%
  ungroup()

# set values to NA during the period when SWC sensor was error 8 Apr to 28 Apr
BB_met[BB_met$date >= "2021-04-8" & BB_met$date <= "2021-04-28", "SWC"] <- NA

# set period
y_2015_2016 <- BB_met$date >= "2015-06-20" & BB_met$date < "2016-06-20"
y_2016_2017 <- BB_met$date >= "2016-06-20" & BB_met$date < "2017-06-20"
y_2017_2018 <- BB_met$date >= "2017-06-20" & BB_met$date < "2018-06-20"
y_2018_2019 <- BB_met$date >= "2018-06-20" & BB_met$date < "2019-06-20"
y_2019_2020 <- BB_met$date >= "2019-06-20" & BB_met$date < "2020-06-20"
y_2020_2021 <- BB_met$date >= "2020-06-20" & BB_met$date < "2021-06-20"


BB_met$period[y_2015_2016] <- "2015-2016"
BB_met$period[y_2016_2017] <- "2016-2017"
BB_met$period[y_2017_2018] <- "2017-2018"
BB_met$period[y_2018_2019] <- "2018-2019"
BB_met$period[y_2019_2020] <- "2019-2020"
BB_met$period[y_2020_2021] <- "2020-2021"

# set season 
GS <- BB_met$month_local %in% c(4, 5, 6, 7, 8, 9)
NGS <- BB_met$month_local %in% c(10, 11, 12, 1, 2, 3)
BB_met$season[GS] <- "growing season"
BB_met$season[NGS] <- "non-growing season"

  
met_monthly <- BB_met %>% 
  ddply("floor_date", summarize, 
      # length = length(TS.5),
      TS.5 = mean(TS.5, na.rm = T),  # soil temp
      TS.10 = mean(TS.10, na.rm = T),
      TS.50 = mean(TS.50, na.rm = T),
      RH = mean(RH, na.rm = T),  # relative humidity
      PARin = mean(PARin, na.rm = T),  #u mol m-2 day-1
      SWin = mean(SWin, na.rm = T),
      VPD.y = mean(VPD.y, na.rm = T),
      # VPD.x = mean(VPD.x),
      Precip = sum(Precip, na.rm = T), # mm per month
      # PA_EC = mean(PA_EC),  # barrometric pressure from EC
      PA_2M = mean(PA_2M, na.rm = T),  # barrometric pressure from met
      Ta = mean(Ta, na.rm = T),  # air temp at 2 m
      SWC = mean(SWC, na.rm = T), 
      wtd = mean(wtd, na.rm = T)) %>%
  mutate(month_local = month(floor_date))

met_monthly_means <- met_monthly %>% 
  ddply("month_local", summarize, 
      TS.5 = mean(TS.5, na.rm = T),  # soil temp
      TS.10 = mean(TS.10, na.rm = T),
      TS.50 = mean(TS.50, na.rm = T),
      RH = mean(RH, na.rm = T),  # relative humidity
      PARin = mean(PARin, na.rm = T),  
      SWin = mean(SWin, na.rm = T),
      VPD.y = mean(VPD.y, na.rm = T),
      # VPD.x = mean(VPD.x),
      Precip = mean(Precip, na.rm = T),
      # PA_EC = mean(PA_EC),  # barrometric pressure from EC
      PA_2M = mean(PA_2M, na.rm = T),  # barrometric pressure from met
      Ta = mean(Ta, na.rm = T),  # air temp at 2 m
      SWC = mean(SWC, na.rm = T), 
      wtd = mean(wtd, na.rm = T))

met_monthly_anom <- met_monthly
# for(i in 1:nrow(met_monthly)){ 
#   met_monthly_anom[i, c(3:14)] <- met_monthly_anom[i, c(3:14)] -  
#     met_monthly_means[met_monthly$month_local[i], c(2:13)]
#   }
for(i in 1:nrow(met_monthly_anom)){
  index <- which(met_monthly_means$month_local == met_monthly_anom$month_local[i])
  met_monthly_anom[i, c(2:13)] <- met_monthly_anom[i, c(2:13)] -
    met_monthly_means[index, c(2:13)]
  # print(i)
  }


```

```{r plotting met variables, message = F, warning = F}

### soil temperature ###

outliers <- boxplot(BB_met$TS.5, plot=FALSE)$out
TS_no_out <- BB_met[-which(BB_met$TS.5 %in% outliers),]
(TS <- TS_no_out %>% 
  # filter(date <= "2020-01-01") %>%
  ggplot() +
  geom_line(aes(x = date, y = TS.5, colour = "5 cm")) + 
  geom_line(aes(x = date, y = TS.10, colour = "10 cm")) +
  geom_line(aes(x = date, y = TS.50, colour = "50 cm")) + 
  scale_color_manual(values = c("5 cm" = "orange1", 
                                "10 cm" = "orangered1", 
                                "50 cm" = "red4"))+
  labs(x = "time", 
       y = expression('Soil temperature ('*~degree*C*')'), 
       colour = "")) + 
  theme_bw()

### relative humidity ###
(RH <- plot_daily(data = BB_met, 
                  variable = RH, 
                  label = "Relative humidity (%)", 
                  ma = 1)) 

### barrometric pressure ###
(PA <- plot_daily(data = BB_met, 
                  variable = PA_2M, 
                  label = "Barrometric pressure (%)", 
                  ma = 1)) 
(SWC <- plot_daily(data = BB_met, 
                  variable = SWC, 
                  label = bquote('soil water content (' ~m^3~ m^-3*')'), 
                  ma = 1))
(Ta <- plot_daily(data = BB_met, 
                  variable = Ta, 
                  label = expression('Air temperature ('*~degree*C*')'), 
                  ma = 1))
(PARin <- plot_daily(data = BB_met, 
                  variable = PARin, 
                  label = expression("PAR ("*mu*"mol"~m^{-2}~s^{-2}*")"), 
                  ma = 1))
(VPD <- plot_daily(data = BB_met, 
                  variable = VPD.y, 
                  label = "VPD", 
                  ma = 1))

(wtd <- BB_met %>% 
  # filter(date <= "2020-01-01") %>%
  ggplot() +
  geom_line(aes(x = date, y = wtd), col = "black") + 
  labs(x = "time", 
       y = "WTD (cm)") + 
  theme_bw())

  
```




# Monthly

## Monthly $CO_2$ & $CH_4$ fluxes

```{r plot monthly fluxes, fig.height = 8, fig.width = 8, message = F, warning = F}
# flux_labels <- c(
#   bquote('NEE (g C' ~m^-2~ day^-1*')'),
#   bquote('GPP (g C' ~m^-2~ day^-1*')'),
#   bquote('Reco (g C' ~m^-2~ day^-1*')'),
#   bquote('CH4 flux - random forest (g C' ~m^-2~ day^-1*')')
# )

flux_labels <- c(
  'NEE (gC m-2 month-1)',
  'GPP (gC m-2 month-1)',
  'Re (gC m-2 month-1)',
  'CH4 flux (gC m-2 month-1)'
)

# monthly_long <- monthly %>%
#   pivot_longer(cols = NEEgC_f_RF:CH4gC_f_RF, names_to = "variable", values_to = "value") %>% 
#   mutate(month = as.yearmon(floor_date),
#          # month_local = factor(month_local, levels = c(1:12)),
#          # month_abb = factor(month.abb[month_local], levels = month.abb), 
#          variable_lab = factor(variable, 
#                            levels = c("NEEgC_f_RF", "GPPgC_f_RF", "RecogC", "CH4gC_f_RF"),
#                            labels = flux_labels))
# 
# monthly_means_long <- monthly_means %>% 
#   pivot_longer(cols = NEEgC_f_RF:CH4gC_f_RF, names_to = "variable", values_to = "value") %>% 
#   mutate(month = as.yearmon(floor_date),
#          # month_local = factor(month_local, levels = c(1:12)),
#          # month_abb = factor(month.abb[month_local], levels = month.abb), 
#          variable_lab = factor(variable, 
#                            levels = c("NEEgC_f_RF", "GPPgC_f_RF", "RecogC", "CH4gC_f_RF"),
#                            labels = flux_labels))
# 
# monthly_anom_long <- monthly_anom %>% 
#   pivot_longer(cols = NEEgC_f_RF:CH4gC_f_RF, names_to = "variable", values_to = "value") %>% 
#   mutate(month = as.yearmon(floor_date),
#          # month_local = factor(month_local, levels = c(1:12)),
#          # month_abb = factor(month.abb[month_local], levels = month.abb), 
#          variable_lab = factor(variable, 
#                            levels = c("NEEgC_f_RF", "GPPgC_f_RF", "RecogC", "CH4gC_f_RF"),
#                            labels = flux_labels))
# 
# ggplotly(plot_monthly(monthly_long, monthly_means_long))

NEE <- daily%>%
ggplot() +
  geom_bar(data = monthly_anom, aes(x = floor_date, y = NEEgC_f_RF/15), fill = "gray", stat = "identity") +
  geom_line(aes(x = date, y = rollmean(NEEgC_f_RF, 7, fill = NA))) +
  scale_y_continuous(
    # limits = c(-4, 2),
    name = expression('NEE (g C' ~m^-2~ d^-1*')'),
    sec.axis = sec_axis(~.*15, name = bquote(Delta*~'NEE (g C' ~m^-2~ month^-1*')'))
    ) +
  labs(x = "") +
  scale_x_date(date_breaks = "1 year",
               date_labels = "%b %Y") +
  theme_bw()

GPP <- daily%>%
ggplot() +
  geom_bar(data = monthly_anom, aes(x = floor_date, y = (GPPgC_f_RF/15)), fill = "gray", stat = "identity") +
  geom_line(aes(x = date, y = rollmean(GPPgC_f_RF, 7, fill = NA))) +
  scale_y_continuous(
    # limits = c(-4, 2),
    name = expression('GPP (g C' ~m^-2~ d^-1*')'),
    sec.axis = sec_axis(~.*15, name = bquote(Delta*~'GPP (g C' ~m^-2~ month^-1*')'))
    ) +
  labs(x = "") +
  scale_x_date(date_breaks = "1 year",
               date_labels = "%b %Y") +
  theme_bw()


Reco <- daily%>%
ggplot() +
  geom_bar(data = monthly_anom, aes(x = floor_date, y = RecogC/25), fill = "gray", stat = "identity") +
  geom_line(aes(x = date, y = rollmean(RecogC, 7, fill = NA))) +
  scale_y_continuous(
    # limits = c(-4, 2),
    name = expression('Reco (g C' ~m^-2~ d^-1*')'),
    sec.axis = sec_axis(~.*15, name = bquote(Delta*~'Reco (g C' ~m^-2~ month^-1*')'))
    ) +
  labs(x = "") +
  scale_x_date(date_breaks = "1 year",
               date_labels = "%b %Y") +
  theme_bw()


CH4 <- daily%>%
ggplot() +
  geom_bar(data = monthly_anom, aes(x = floor_date, y = CH4gC_f_RF/10), fill = "gray", stat = "identity") +
  geom_line(aes(x = date, y = rollmean(CH4gC_f_RF, 7, fill = NA))) +
  scale_y_continuous(
    name = expression(CH[4]~'(g C' ~m^-2~ d^-1*')'),
    sec.axis = sec_axis(~.*10, name = bquote(Delta*~CH[4]~'(g C' ~m^-2~ month^-1*')'))
    ) +
  labs(x = "") +
  scale_x_date(date_breaks = "1 year",
               date_labels = "%b %Y") +
  theme_bw()


# NEE <- daily%>%
# ggplot() +
#   geom_point(data = BB1, aes(x = date, y = NEE_f_RF/10), color = "gray", stat = "identity") +
#   geom_line(aes(x = date, y = rollmean(NEEgC_f_RF, 7, fill = NA))) +
#   scale_y_continuous(
#     # limits = c(-4, 2),
#     name = expression('NEE (g C' ~m^-2~ d^-1*')'),
#     sec.axis = sec_axis(~.*10, name = bquote("NEE ("*mu*~"mol"~m^-2~ s^-1*')'))
#     ) +
#   labs(x = "") +
#   scale_x_date(date_breaks = "1 year", 
#                date_labels = "%b %Y") +
#   theme_bw()
# 
# GPP <- daily%>%
# ggplot() +
#   geom_point(data = BB1, aes(x = date, y = GPP_f_RF/5), color = "gray", stat = "identity") +
#   geom_line(aes(x = date, y = rollmean(GPPgC_f_RF, 7, fill = NA))) +
#   scale_y_continuous(
#     # limits = c(-4, 2),
#     name = expression('GPP (g C' ~m^-2~ d^-1*')'), 
#     sec.axis = sec_axis(~.*5, name = bquote("GPP ("*mu*~"mol"~m^-2~ s^-1*')'))
#     ) +
#   labs(x = "") +
#   scale_x_date(date_breaks = "1 year", 
#                date_labels = "%b %Y") +
#   theme_bw()
# 
# 
# Reco <- daily%>%
# ggplot() +
#   geom_point(data = BB1, aes(x = date, y = Reco), color = "gray", stat = "identity") +
#   geom_line(aes(x = date, y = rollmean(RecogC, 7, fill = NA))) +
#   scale_y_continuous(
#     # limits = c(-4, 2),
#     name = expression('Reco (g C' ~m^-2~ d^-1*')'), 
#     sec.axis = sec_axis(~., name = bquote("Reco ("*mu*~"mol"~m^-2~ s^-1*')'))
#     ) +
#   labs(x = "") +
#   scale_x_date(date_breaks = "1 year", 
#                date_labels = "%b %Y") +
#   theme_bw()
# 
# 
# CH4 <- daily%>%
# ggplot() +
#   geom_point(data = BB1, aes(x = date, y = FCH4_gf_RF/5), color = "gray", stat = "identity") +
#   geom_line(aes(x = date, y = rollmean(CH4gC_f_RF, 7, fill = NA))) +
#   scale_y_continuous(
#     name = expression(F[CH4]~'(g C' ~m^-2~ d^-1*')'), 
#     sec.axis = sec_axis(~.*5, name = bquote(F[CH4]~"("*mu*"mol"~m^-2~ s^-1*')'))
#     ) +
#   labs(x = "") +
#   scale_x_date(date_breaks = "1 year", 
#                date_labels = "%b %Y") +
#   theme_bw()


print(NEE)
ggsave("plots/NEE_daily.png")
print(GPP)
ggsave("plots/GPP_daily.png")
print(Reco)
ggsave("plots/Reco_daily.png")
print(CH4)
ggsave("plots/CH4_daily.png")
```

## Cumulative NEE, GPP, Reco 

```{r}
## plot cumulative 

fluxcum_labels <- c(
  bquote(NEE~'(g C' ~m^-2~')'),
  bquote(GPP~'(g C' ~m^-2~')'),
  bquote(Reco~'(g C' ~m^-2~')'),
  bquote(CH[4]~'(g C' ~m^-2~')')
)

# fluxcum_labels <- c(
#   'Cumulative NEE (gC m-2)',
#   'Cumulative GPP (gC m-2)',
#   'Cumulative Re (gC m-2)',
#   'Cumulative CH4 (gC m-2)'
# )

flux_cum <- cumsum %>% 
  select(c(date, cumNEE_RF, cumGPP_RF, cumReco, cumCH4, period, floor_date)) %>%
  pivot_longer(cols = c(cumNEE_RF, cumGPP_RF, cumReco, cumCH4), names_to = "variable", values_to = "value") %>%
  mutate(variable_lab = factor(variable, 
                           levels = c("cumNEE_RF", "cumGPP_RF", 
                                      "cumReco", "cumCH4"),
                           labels = fluxcum_labels)) %>% 
  group_by(variable,period) %>%
  arrange(date) %>%
  mutate(order = row_number()) %>% 
  ungroup() %>% 
  mutate(day_label = case_when(day(date) == 1L ~ format(date, "%b"),
                     TRUE ~ NA_character_)
         )
  
  
x_break <- flux_cum$order[!is.na(flux_cum$day_label)][1:48]
x_label <- flux_cum$day_label[!is.na(flux_cum$day_label)][1:48]
x_label

flux_cum %>% 
  ggplot(aes(x = order, y = value, color = factor(period), group = factor(period))) + 
  geom_line(size = 1) + 
  facet_wrap(vars(variable_lab), ncol = 1,
               scales = "free_y",
               strip.position = "left", 
               labeller = label_parsed
             ) +
  labs(x = "", y = "", color = "Year") +
  scale_x_continuous(
    breaks = unique(x_break),
    labels = unique(x_label)) +
  theme_bw() +
  theme(strip.background = element_blank(),
        strip.placement = "outside")
ggsave("plots/cumulative_flux.png")
```

## monthly met variables
```{r plot monthly met, fig.height = 10, fig.width = 8, message = F, warning = F} 
# met_labels <- c(
#   bquote(T[s]~'at 5 cm'),
#   # bquote('NEE (g C' ~m^-2~ day^-1*')'),
#   bquote(T[s]~'at 10 cm'),
#   bquote(T[s]~'at 50 cm'),
#   expression('RH("%")'), 
#   expression("PAR ("*mu*"mol"~m^{-2}~s^{-2}*")"), 
#   expression('Incoming~Shortwave'), 
#   expression('VPD'), 
#   expression('Precipitation~(mm)'), 
#   expression('Barrometric~pressure~("%")'), 
#   expression('Air temperature ('*~degree*C*')'), 
#   expression('WTD~before~~2018'), 
#   expression('WTD~after~~2018'), 
#   bquote('soil~water~content~(' ~m^3~ m^-3*')'), 
#   expression('WTD')
#   )

met_labels <- c(
  'Ts at 5 cm (C)',
  # bquote('NEE (g C' ~m^-2~ day^-1*')'),
  'Ts at 10 cm (C)',
  'Ts at 50 cm (C)',
  'RH("%")', 
  "PAR u mol m-2 s-2", 
  'Incoming Shortwave', 
  'VPD', 
  'Precipitation (mm)', 
  'Pa (%)', 
  'Ta (C)', 
  'WTD before 2018', 
  'WTD after 2018', 
  'SWC(m3 m-3)', 
  'WTD (cm)'
  )


# met_monthly_long <- met_monthly %>%
#   pivot_longer(cols = TS.5:wtd, names_to = "variable", values_to = "value") %>% 
#   mutate(month_local = factor(month_local, levels = c(1:12)),
#          month_abb = factor(month.abb[month_local], levels = month.abb), 
#          variable_lab = factor(variable, 
#                            levels = colnames(met_monthly)[3:16],
#                            labels = met_labels))
# 
# met_monthly_means_long <- met_monthly_means %>% 
#   pivot_longer(cols = TS.5:wtd, names_to = "variable", values_to = "value") %>% 
#   mutate(month_local = factor(month_local, levels = c(1:12)),
#          month_abb = factor(month.abb[month_local], levels = month.abb), 
#          variable_lab = factor(variable, 
#                           levels = colnames(met_monthly)[3:16],
#                           labels = met_labels))
# 
# temp <-  plot_monthly(filter(met_monthly_long, 
#                              variable %in% c("TS.5", "TS.10", "TS.50", "PARin", "SWin", "Ta")), 
#                       filter(met_monthly_means_long,
#                              variable %in% c("TS.5", "TS.10", "TS.50", "PARin", "SWin", "Ta")))
# 
# water <-  plot_monthly(filter(met_monthly_long, 
#                              variable %in% c("Precip", "wtd", "VPD.y", "SWC", "RH")), 
#                       filter(met_monthly_means_long,
#                              variable %in% c("Precip", "wtd", "VPD.y", "SWC", "RH")))

TS5cm <- BB_met%>%
ggplot() +
  geom_bar(data = met_monthly_anom, aes(x = floor_date, y = TS.5*5), fill = "gray", stat = "identity") +
  geom_line(aes(x = date, y = rollmean(TS.5, 7, fill = NA))) +
  scale_y_continuous(
    # limits = c(-4, 2),
    name = bquote(T[s~5~cm]~'('*degree*'C)'),
    sec.axis = sec_axis(~./5, name = bquote(Delta*~T[s~5~cm]~'('*degree*'C)'))
    ) +
  labs(x = "") +
  scale_x_date(date_breaks = "1 year", 
               date_labels = "%b %Y") +
  theme_bw()

Tair <- BB_met%>%
ggplot() +
  geom_bar(data = met_monthly_anom, aes(x = floor_date, y = Ta*5), fill = "gray", stat = "identity") +
  geom_line(aes(x = date, y = rollmean(Ta, 7, fill = NA))) +
  scale_y_continuous(
    # limits = c(0, 30),
    name = bquote(T[air]~'('*degree*'C)'),
    sec.axis = sec_axis(~./5, name = bquote(Delta*~T[air]~'('*degree*'C)'))
    ) +
  labs(x = "") +
  scale_x_date(date_breaks = "1 year", 
               date_labels = "%b %Y") +
  theme_bw()

wtd <- BB_met%>%
ggplot() +
  geom_bar(data = met_monthly_anom, aes(x = floor_date, y = wtd*100), fill = "gray", stat = "identity") +
  geom_line(aes(x = date, y = wtd*100)) +
  scale_y_continuous(
    # limits = c(0, 30),
    name = "WTD (cm)",
    sec.axis = sec_axis(~., name = bquote(Delta*~"WTD (cm)"))
    ) +
  labs(x = "") +
  scale_x_date(date_breaks = "1 year", 
               date_labels = "%b %Y") +
  theme_bw()

PARin <- BB_met%>%
ggplot() +
  geom_bar(data = met_monthly_anom, aes(x = floor_date, y = PARin*2), fill = "gray", stat = "identity") +
  geom_line(aes(x = date, y = rollmean(PARin, 7, fill = NA))) +
  scale_y_continuous(
    # limits = c(0, 30),
    name = bquote("PAR ("~mu~mol~m^{-2}~d^{-1}~")"),
    sec.axis = sec_axis(~./2, name = bquote(Delta*~"PAR ("~mu~mol~m^{-2}~d^{-1}~")"))
    ) +
  labs(x = "") +
  scale_x_date(date_breaks = "1 year", 
               date_labels = "%b %Y") +
  theme_bw()

precip <- BB_met%>%
ggplot() +
  geom_bar(data = met_monthly_anom, aes(x = floor_date, y = Precip/10), fill = "gray", stat = "identity") +
  geom_bar(aes(x = date, y = rollmean(Precip, 7, fill = NA)), stat = "identity", fill = "black") +
  scale_y_continuous(
    # limits = c(0, 30),
    name = bquote("Precipitation (mm"~d^-1~")"),
    sec.axis = sec_axis(~.*10, name = bquote(Delta*"Precip (mm"~month^-1~")"))
    ) +
  labs(x = "") +
  scale_x_date(date_breaks = "1 year", 
               date_labels = "%b %Y") +
  theme_bw()

VPD <- BB_met%>%
ggplot() +
  geom_bar(data = met_monthly_anom, aes(x = floor_date, y = VPD.y*2), fill = "gray", stat = "identity") +
  geom_line(aes(x = date, y = rollmean(VPD.y, 7, fill = NA))) +
  scale_y_continuous(
    # limits = c(0, 30),
    name = bquote("VPD (hPa"~d^-1~")"),
    sec.axis = sec_axis(~./2, name = bquote(Delta*~"VPD (hPa"~d^-1~")"))
    ) +
  labs(x = "") +
  scale_x_date(date_breaks = "1 year", 
               date_labels = "%b %Y") +
  theme_bw()

print(TS5cm)
ggsave("plots/TS5cm.png")
print(Tair)
ggsave("plots/Tair.png")
print(wtd)
ggsave("plots/wtd.png")
print(PARin)
ggsave("plots/PARin.png")
print(VPD)
ggsave("plots/vpd.png")
print(precip)
ggsave("plots/precip.png")

ggplotly(water)

```

## Annual 

```{r, message = F, warning = F}

day_count <- daily %>%
  drop_na(c(NEEgC_f_RF, RecogC, GPPgC_f_RF, CH4gC_f_RF)) %>%
  dplyr::count(period)
# 
# flux_an_means <- daily %>%
#   group_by(year_local) %>%
#   summarise(NEEgC_f = mean(NEEgC_f, na.rm = T) * 365,
#             RecogC = mean(RecogC, na.rm = T) * 365,
#             GPPgC_f = mean(GPPgC_f, na.rm = T) * 365, 
#             CH4_gC = mean(CH4gC_f_RF, na.rm = T) * 365) %>%
#   ungroup() %>%
#   mutate(day_count = day_count$n)
#   # filter(day_count > 200)

flux_an_sum <- daily %>%
  group_by(period) %>%
  summarise(NEEgC_f_RF = sum(NEEgC_f_RF, na.rm = T),
            RecogC = sum(RecogC, na.rm = T),
            GPPgC_f_RF = sum(GPPgC_f_RF, na.rm = T), 
            CH4_gC_RF = sum(CH4gC_f_RF, na.rm = T)) %>%
  ungroup() %>%
  mutate(day_count = day_count$n) %>% 
  drop_na()
  # filter(day_count > 200)

# set season 
daily$season <- NA
GS <- daily$month_local %in% c(4, 5, 6, 7, 8, 9)
NGS <- daily$month_local %in% c(10, 11, 12, 1, 2, 3)
daily$season[GS] <- "growing season"
daily$season[NGS] <- "non-growing season"

flux_season_sum <- daily %>%
  group_by(period, season) %>%
  summarise(NEEgC_f_RF = sum(NEEgC_f_RF, na.rm = T),
            RecogC = sum(RecogC, na.rm = T),
            GPPgC_f_RF = sum(GPPgC_f_RF, na.rm = T), 
            CH4_gC_RF = sum(CH4gC_f_RF, na.rm = T)) %>%
  ungroup()%>% 
  drop_na()

met_an_means <- BB_met %>%
  # mutate(year_local = year(date)) %>%
  group_by(period) %>%
  summarise(TS.5 = mean(TS.5, na.rm = T),  # soil temp
      TS.10 = mean(TS.10, na.rm = T),
      TS.50 = mean(TS.50, na.rm = T),
      RH = mean(RH, na.rm = T),  # relative humidity
      PARin = sum(PARin, na.rm = T),  
      SWin = mean(SWin, na.rm = T),
      VPD = mean(VPD.y, na.rm = T),
      # VPD.x = mean(VPD.x, na.rm = T),
      Precip = sum(Precip, na.rm = T),
      # PA_EC = mean(PA_EC, na.rm = T),  # barrometric pressure from EC
      PA = mean(PA_2M, na.rm = T),  # barrometric pressure from met
      Ta = mean(Ta, na.rm = T),  # air temp at 2 m
      # WTH2 = mean(WTH2, na.rm = T),
      # WTH1 = mean(WTH1, na.rm = T),  # water table height
      SWC = mean(SWC, na.rm = T), 
      wtd = mean(wtd, na.rm = T)) %>%
  ungroup()%>% 
  drop_na()

met_season_sum <- BB_met %>%
  group_by(period, season) %>%
  summarise(TS.5 = mean(TS.5, na.rm = T),  # soil temp
      TS.10 = mean(TS.10, na.rm = T),
      TS.50 = mean(TS.50, na.rm = T),
      RH = mean(RH, na.rm = T),  # relative humidity
      PARin = sum(PARin, na.rm = T),  
      SWin = mean(SWin, na.rm = T),
      VPD = mean(VPD.y, na.rm = T),
      # VPD.x = mean(VPD.x, na.rm = T),
      Precip = sum(Precip, na.rm = T),
      # PA_EC = mean(PA_EC, na.rm = T),  # barrometric pressure from EC
      PA = mean(PA_2M, na.rm = T),  # barrometric pressure from met
      Ta = mean(Ta, na.rm = T),  # air temp at 2 m
      # WTH2 = mean(WTH2, na.rm = T),
      # WTH1 = mean(WTH1, na.rm = T),  # water table height
      SWC = mean(SWC, na.rm = T), 
      wtd = mean(wtd, na.rm = T)) %>%
  ungroup()%>% 
  drop_na()

  
kable(flux_an_sum, caption = "Cumulative annual fluxes", 
    col.names = c("year", 
                  "NEE (gC m^2^ year^-1^)", 
                  "Reco (gC m^2^ year^-1^)", 
                  "GPP (gC m^2^ year^-1^)", 
                  "CH~4~ (gC m^2^ year^-1^)", 
                  "day_count")) %>% 
kable_styling()

kable(met_an_means, caption = "Annual met variables", 
      col.names = c("year", 
                    "T~s~~5cm~", 
                    "T~s~~10cm~",
                    "T~s~~50cm~", 
                    "RH(%)", 
                    "PAR", 
                    "SW~in~", 
                    "VPD", 
                    "Precip", 
                    "PA", 
                    "T~a~", 
                    "SWC",
                    "WTD")) %>%
kable_styling()


write.csv(flux_an_sum, "flux_annual_summary.csv")
write.csv(flux_season_sum, "flux_season_summary.csv")
# write.csv(met_an_sum, "met_annual_summary.csv")
write.csv(met_an_means, "met_annual_summary.csv")
write.csv(met_season_sum, "met_season_summary.csv")

```

```{r check annual pattern, message = F, warning = F}
# plot_monthly <- function(main_data, mean_data){
#   main_data%>%
#   ggplot() +
#     geom_bar(aes(x = month_abb, y = value, fill = as.factor(year_local)), 
#              position = position_dodge(), stat="identity") +
#     geom_line(data = mean_data, aes(x = month_abb, y = value, group = 1)) +
#     geom_point(data = mean_data, aes(x = month_abb, y = value, group = 1)) +
#     facet_wrap(vars(variable_lab), ncol = 1,
#                scales = "free_y",
#                strip.position = "left", 
#                # labeller = label_parsed
#                ) +
#     labs(x = "", y = "", fill = "Year") +
#     theme_bw()+
#     theme(strip.background = element_blank(),
#           strip.placement = "outside") 
# }


# correlation for annual values
corr <- left_join(met_an_means, flux_an_sum) %>%
  mutate(year = substr(period, 1, 4))
# ggscatter(corr, x = "wtd", y = "NEEgC_f_RF",
#           add = "reg.line", conf.int = TRUE,
#           cor.coef = T, cor.method = "pearson",
#           xlab = "wtd", ylab = "cumNEE")

# correlation for growing & non-growing season
corr_GS <- left_join(filter(flux_season_sum, season == "growing season"), filter(met_season_sum, season == "growing season"))%>%
  mutate(year = substr(period, 1, 4))

corr_NGS <- left_join(filter(flux_season_sum, season == "non-growing season"), filter(met_season_sum, season == "non-growing season"))%>%
  mutate(year = substr(period, 1, 4))



flux_loop <- c("NEEgC_f_RF", "RecogC", "GPPgC_f_RF", "CH4_gC_RF")
met_loop <- c("TS.5", "Ta", "VPD", "wtd", "PARin", "Precip", "GPPgC_f_RF")


###### for annual correlation ########
for (i in flux_loop) {
  for (j in met_loop) { 
    eval(parse(text = paste0(i, '_vs_' , j, '<- corr %>% ggplot(aes_string(x = "', j,'", y = "',i,'")) + 
    geom_point(size = 3) + 
  geom_text(aes(label=year), size = 3, hjust=0.5, vjust=-0.8) +
  labs(x = "', j,'", y = "',i,'",  col= "") +  
  theme_bw() + 
  theme(legend.position="none")'
                             )))
    eval(parse(text = paste0("print(",i,"_vs_",j,")")))
    eval(parse(text = paste0("ggsave('plots/nocorr_",i,"_vs_",j,".png')")))
  }
}

## add correlation and regression line
for (i in flux_loop) {
  for (j in met_loop) { 
    eval(parse(text = paste0(i, '_vs_' , j, '<- corr %>% ggplot(aes_string(x = "', j,'", y = "',i,'")) + 
    geom_point(size = 3) + 
  geom_smooth(method = "lm", se = F, col = "black") +
  geom_text(aes(label=year), size = 3, hjust=0.5, vjust=-0.8) +
  labs(x = "', j,'", y = "',i,'",  col= "") +  
  stat_cor(size = 3.5) +
  theme_bw()+ 
  theme(legend.position="none")')))
    eval(parse(text = paste0("print(",i,"_vs_",j,")")))
    eval(parse(text = paste0("ggsave('plots/corr_",i,"_vs_",j,".png')")))
  }
}
  


###### for growing season correlation ########
## add correlation and regression line
for (i in flux_loop) {
  for (j in met_loop) { 
    eval(parse(text = paste0(i, '_vs_' , j, '<- corr_GS %>% ggplot(aes_string(x = "', j,'", y = "',i,'")) + 
    geom_point(size = 3) + 
  geom_smooth(method = "lm", se = F, col = "black") +
  ggtitle("GS") + 
  geom_text(aes(label=year), size = 3, hjust=0.5, vjust=-0.8) +
  labs(x = "', j,'", y = "',i,'",  col= "") +  
  stat_cor(size = 3.5) +
  theme_bw()+ 
  theme(legend.position="none")')))
    eval(parse(text = paste0("print(",i,"_vs_",j,")")))
    eval(parse(text = paste0("ggsave('plots/corr_GS_",i,"_vs_",j,".png')")))
  }
}


###### for non-growing season correlation #####
for (i in flux_loop) {
  for (j in met_loop) { 
    eval(parse(text = paste0(i, '_vs_' , j, '<- corr_NGS %>% ggplot(aes_string(x = "', j,'", y = "',i,'")) + 
    geom_point(size = 3) + 
  geom_smooth(method = "lm", se = F, col = "black") +
  ggtitle("NGS") + 
  geom_text(aes(label=year), size = 3, hjust=0.5, vjust=-0.8) +
  labs(x = "', j,'", y = "',i,'",  col= "") +  
  stat_cor(size = 3.5) +
  theme_bw()+ 
  theme(legend.position="none")')))
    eval(parse(text = paste0("print(",i,"_vs_",j,")")))
    eval(parse(text = paste0("ggsave('plots/corr_NGS_",i,"_vs_",j,".png')")))
  }
}

grid.arrange(ncol = 3, 
             NEEgC_f_RF_vs_PARin, 
             NEEgC_f_RF_vs_Ta, 
             NEEgC_f_RF_vs_TS.5, 
             NEEgC_f_RF_vs_VPD, 
             NEEgC_f_RF_vs_wtd, 
             NEEgC_f_RF_vs_Precip)

grid.arrange(ncol = 3, 
             RecogC_vs_PARin, 
             RecogC_vs_Ta, 
             RecogC_vs_TS.5, 
             RecogC_vs_VPD, 
             RecogC_vs_wtd, 
             RecogC_vs_Precip)

grid.arrange(ncol = 3, 
             GPPgC_f_RF_vs_PARin, 
             GPPgC_f_RF_vs_Ta, 
             GPPgC_f_RF_vs_TS.5, 
             GPPgC_f_RF_vs_VPD, 
             GPPgC_f_RF_vs_wtd, 
             GPPgC_f_RF_vs_Precip)

grid.arrange(ncol = 3, 
             CH4_gC_RF_vs_PARin, 
             CH4_gC_RF_vs_Ta, 
             CH4_gC_RF_vs_TS.5, 
             CH4_gC_RF_vs_VPD, 
             CH4_gC_RF_vs_wtd, 
             CH4_gC_RF_vs_Precip)


```


```{r compare two WTD types}

## check which WTD correction type makes more sense

# plot wtd2 vs wtd
corr %>% ggplot(aes(x = wtd, y = wtd2)) + 
    geom_point(aes(col = factor(period), label = factor(period)), size = 3) + 
  geom_smooth(method = "lm", se = F, col = "black") +
  labs(x = "wtd", y = "wtd2",  col= "") +  
  stat_cor(size = 3.5) +
  theme_bw()

# plot wtd vs precip
corr %>% ggplot(aes(x = wtd, y = Precip)) + 
    geom_point(aes(col = factor(period), label = factor(period)), size = 3) + 
  geom_smooth(method = "lm", se = F, col = "black") +
  labs(x = "wtd", y = "precip",  col= "") +  
  stat_cor(size = 3.5) +
  theme_bw()

# plot wtd2 vs precip
corr %>% ggplot(aes(x = wtd2, y = Precip)) + 
    geom_point(aes(col = factor(period), label = factor(period)), size = 3) + 
  geom_smooth(method = "lm", se = F, col = "black") +
  labs(x = "wtd2", y = "precip",  col= "") +  
  stat_cor(size = 3.5) +
  theme_bw()


# plot wtd vs SWC
corr %>% ggplot(aes(x = wtd, y = SWC)) + 
    geom_point(aes(col = factor(period)), size = 3) + 
  geom_smooth(method = "lm", se = F, col = "black") +
  labs(x = "wtd", y = "SWC",  col= "") +  
  stat_cor(size = 3.5) +
  theme_bw()

# plot wtd2 vs SWC
corr %>% ggplot(aes(x = wtd2, y = SWC)) + 
    geom_point(aes(col = factor(period)), size = 3) + 
  geom_smooth(method = "lm", se = F, col = "black") +
  labs(x = "wtd2", y = "SWC",  col= "") +  
  stat_cor(size = 3.5) +
  theme_bw()



# plot daily wtd vs SWC
BB_met %>% 
  filter(period == "2016-2017") %>%
  ggplot(aes(x = wtd, y = SWC)) + 
  geom_point() +
  geom_smooth(method = "lm", se = F, col = "black") + 
  labs(x = "daily wtd", y = "daily SWC", col = "") + 
  stat_cor(size = 3.5) + 
  theme_bw()

# plot timeseries of SWC & WTD
plot_ly(data = BB_met, x = ~date, y = ~SWC, name = 'SWC', type = 'scatter', mode = 'lines') %>%
  add_trace( x = ~date, y = ~wtd, name = 'wtd', type = 'scatter', mode = 'lines') %>% 
    add_trace( x = ~date, y = ~wtd2, name = 'wtd', type = 'scatter', mode = 'lines') 


###### for Growing season ####

# plot wtd2 vs wtd
corr_GS %>% ggplot(aes(x = wtd, y = wtd2)) + 
    geom_point(aes(col = factor(period), label = factor(period)), size = 3) + 
  geom_smooth(method = "lm", se = F, col = "black") +
  labs(title = "growing season", x = "wtd", y = "wtd2",  col= "") +  
  stat_cor(size = 3.5) +
  theme_bw()

# plot wtd vs precip
corr_GS %>% ggplot(aes(x = wtd, y = Precip)) + 
    geom_point(aes(col = factor(period)), size = 3) + 
  geom_smooth(method = "lm", se = F, col = "black") +
  labs(title = "growing season", x = "wtd", y = "precip",  col= "") +  
  stat_cor(size = 3.5) +
  theme_bw()

# plot wtd2 vs precip
corr_GS %>% ggplot(aes(x = wtd2, y = Precip)) + 
    geom_point(aes(col = factor(period)), size = 3) + 
  geom_smooth(method = "lm", se = F, col = "black") +
  labs(title = "growing season", x = "wtd2", y = "precip",  col= "") +  
  stat_cor(size = 3.5) +
  theme_bw()

# plot wtd vs SWC
corr_GS %>% ggplot(aes(x = wtd, y = SWC)) + 
    geom_point(aes(col = factor(period)), size = 3) + 
  geom_smooth(method = "lm", se = F, col = "black") +
  labs(x = "wtd", y = "SWC",  col= "") +  
  stat_cor(size = 3.5) +
  theme_bw()

# plot wtd2 vs SWC
corr_GS %>% ggplot(aes(x = wtd2, y = SWC)) + 
    geom_point(aes(col = factor(period)), size = 3) + 
  geom_smooth(method = "lm", se = F, col = "black") +
  labs(x = "wtd2", y = "SWC",  col= "") +  
  stat_cor(size = 3.5) +
  theme_bw()




###### for Non-Growing season ####

# plot wtd2 vs wtd
corr_NGS %>% ggplot(aes(x = wtd, y = wtd2)) + 
    geom_point(aes(col = factor(period), label = factor(period)), size = 3) + 
  geom_smooth(method = "lm", se = F, col = "black") +
  labs(title = "non-growing season", x = "wtd", y = "wtd2",  col= "") +  
  stat_cor(size = 3.5) +
  theme_bw()

# plot wtd vs precip
corr_NGS %>% ggplot(aes(x = wtd, y = Precip)) + 
    geom_point(aes(col = factor(period), label = factor(period)), size = 3) + 
  geom_smooth(method = "lm", se = F, col = "black") +
  labs(title = "non-growing season", x = "wtd", y = "precip",  col= "") +  
  stat_cor(size = 3.5) +
  theme_bw()

# plot wtd2 vs precip
corr_NGS %>% ggplot(aes(x = wtd2, y = Precip)) + 
    geom_point(aes(col = factor(period), label = factor(period)), size = 3) + 
  geom_smooth(method = "lm", se = F, col = "black") +
  labs(title = "non-growing season", x = "wtd2", y = "precip",  col= "") +  
  stat_cor(size = 3.5) +
  theme_bw()

```

```{r, eval = F, include = F}
# check with Nick 

# Nick <-  daily %>% 
#   filter(date >= "2015-06-16" & date <= "2016-06-15") %>%
#   group_by(year_local, month_local) %>% 
#   summarize(NEEgC_f = sum(NEEgC_f),
#         RecogC = sum(RecogC),
#         GPPgC_f = sum(GPPgC_f), 
#         CH4_gC = sum(CH4gC_f)) %>% 
#   ungroup()
# sum_Nick <- sum(as.numeric(Nick$GPPgC_f))
# sum_Nick /12 * 44

```

```{r, eval = F, include = F}

# Check with Marion 


Marion <- daily %>% 
  filter(year_local == 2020) %>% 
  mutate(cumNEE = cumsum(NEEgC_f), 
         cumReco = cumsum(RecogC),
        cumGPP = cumsum(GPPgC_f), 
        cumCH4 = cumsum(CH4gC_f))
plot_daily(data = Marion, 
           variable = cumNEE, 
           label = expression("cumulative NEE (gC "*m^{-2}~day^{-1}*")"), 
           ma = 1
           )
plot_daily(data = Marion, 
           variable = cumReco, 
           label = expression("cumulative Reco (gC "*m^{-2}~day^{-1}*")"), 
           ma = 1
           )
plot_daily(data = Marion, 
           variable = cumGPP, 
           label = expression("cumulative GPP (gC "*m^{-2}~day^{-1}*")"), 
           ma = 1
           )
plot_daily(data = Marion, 
           variable = cumCH4, 
           label = expression("cumulative CH4 (gC "*m^{-2}~day^{-1}*")"), 
           ma = 1
           )
```

```{r read remote sensing indices}

# read csv exported from GEE
RS_indices <- read.csv("G:/My Drive/Burns_Bog/BB1_GEE_Indices.csv", header = T, skip = 1) %>% 
  select(-1)

# get date from landsat ID
RS_indices$date <- RS_indices$id %>% 
  substr(13, 20) %>%
  as.POSIXct(format = "%Y%m%d")

RS_indices <- left_join(daily, RS_indices)

# add year, month, floor_date
RS_indices <- RS_indices %>% 
  mutate(year_local = year(date), 
         month_local = month(date), 
         floor_date = floor_date(date, "month")) 
# add period
y_2015_2016 <- RS_indices$date >= "2015-06-20" & RS_indices$date < "2016-06-20"
y_2016_2017 <- RS_indices$date >= "2016-06-20" & RS_indices$date < "2017-06-20"
y_2017_2018 <- RS_indices$date >= "2017-06-20" & RS_indices$date < "2018-06-20"
y_2018_2019 <- RS_indices$date >= "2018-06-20" & RS_indices$date < "2019-06-20"
y_2019_2020 <- RS_indices$date >= "2019-06-20" & RS_indices$date < "2020-06-20"
y_2020_2021 <- RS_indices$date >= "2020-06-20" & RS_indices$date < "2021-06-20"

RS_indices$period[y_2015_2016] <- "2015-2016"
RS_indices$period[y_2016_2017] <- "2016-2017"
RS_indices$period[y_2017_2018] <- "2017-2018"
RS_indices$period[y_2018_2019] <- "2018-2019"
RS_indices$period[y_2019_2020] <- "2019-2020"
RS_indices$period[y_2020_2021] <- "2020-2021"

# calculate annual RS indices (mean, peak, median)


```



