---
title: "Prelim"
author: "Tin Satriawan"
date: "20/01/2022"
output: html_document
editor_options: 
  chunk_output_type: console
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

library(plyr)
library(ggplot2)
library(lubridate)
library(naniar)
library(tidyr)
library(plotly)
library(knitr)
library(data.table)
library(kableExtra)
library(ggsci)
library(effects)
library(tidyverse)
library(zoo)
library(caret)
library(ggpubr)
library(gridExtra)
library(lognorm)
library(reshape2)
library(matrixStats)
library(gtools)
library(dplyr)


```







```{r read data, include = F, message = F, warning = F}

# define directory

dir_rf <- "G:\\.shortcut-targets-by-id\\1txCh9lZ7VGCujXGvBaJCMVnuxT-65q4K\\Micromet Lab\\Projects\\2014-Burns Bog\\Flux-tower\\flux_data\\for_uncertainty\\RF_results"

dir_unc <- "G:\\.shortcut-targets-by-id\\1txCh9lZ7VGCujXGvBaJCMVnuxT-65q4K\\Micromet Lab\\Projects\\2014-Burns Bog\\Flux-tower\\flux_data\\for_uncertainty"



## read NEE RF gapfilling with 20x iteration
result_RF_NEE <- readRDS(paste0(dir_rf,"/BB_NEE_rf_result"))
# average over 20 iteration
RF_NEE <- result_RF_NEE %>% pivot_wider(id_cols = DateTime, names_from = iteration, values_from = NEE_RF_filled)
RF_NEE <- data.frame(DateTime = RF_NEE$DateTime, 
                     NEE_RF_filled = rowMeans(RF_NEE[, 2:ncol(RF_NEE)]), 
                     NEE_RF_fsd = rowSds(as.matrix(RF_NEE[, 2:ncol(RF_NEE)])))

## read CH4 RF gapfilling with 20x iteration
result_RF_FCH4 <- read_csv(paste0(dir_rf,"/BB_FCH4_rf_result.csv"))

# read flux & met data
BB1 <- fread(paste0(dir_unc,"/BB_L3.csv"))
BB1[BB1 == -9999] <- NA
BB1$DATE <- as.POSIXct(BB1$DATE, tz = "UTC")
BB1$date <- as.Date(BB1$DATE, format="%Y-%m-%d %H:%M:%S")

BB1 <- BB1 %>%
  mutate(period = NA, 
         season = NA)


# fill long gaps after MDS gapfilling with values from random forest gapfilling
long_gap2 <- BB1$DATE >= as.POSIXct("2015-12-01 00:30:00", tz = "UTC") &
  BB1$DATE < as.POSIXct("2016-02-21 00:30:00", tz = "UTC")
long_gap <- BB1$DATE >= as.POSIXct("2016-10-22 00:30:00", tz = "UTC") &
  BB1$DATE < as.POSIXct("2017-01-21 00:30:00", tz = "UTC")


BB1$NEE_RF <- RF_NEE$NEE_RF_filled  # random forest gapfill
BB1$NEE_f_RF <- BB1$NEE_f
BB1$NEE_RF_fsd <- RF_NEE$NEE_RF_filled_SD

# fill all NA values with values from random forest
BB1$NEE_f_RF[long_gap] <- BB1$NEE_RF[long_gap]
BB1$NEE_f_RF[long_gap2] <- BB1$NEE_RF[long_gap2]


# check if there are still gaps
which(is.na(BB1$NEE_f_RF))


BB1$GPP_f_RF <- BB1$Reco - BB1$NEE_f_RF


# filter date
BB1 <- BB1 %>% 
  filter(DATE >= as.POSIXct("2015-10-01 00:30:00", tz = "UTC") & DATE < as.POSIXct("2021-10-01 00:00:00", tz = "UTC")) 
result_RF_FCH4 <- result_RF_FCH4 %>% 
  filter(DateTime >= as.POSIXct("2015-10-01 00:30:00", tz = "UTC") & DateTime < as.POSIXct("2021-10-01 00:00:00", tz = "UTC")) 
result_RF_NEE <- result_RF_NEE %>% 
  filter(DateTime >= as.POSIXct("2015-10-01 00:30:00", tz = "UTC") & DateTime < as.POSIXct("2021-10-01 00:00:00", tz = "UTC"))


#Conversion factors
ch4_conv <- 12.01/(10^6)
co2_conv <- 12.01/(10^6) 
d.avg <- 1800 * 48  # 60s * 30min * 2 hours * 24 hours

```


# Daily plots 


```{r data wrangling and function , include = F, message = F, warning = F}


########### BB flux ############

BB_flux <- BB1 %>%
  select (c(DATE, date, jday, month_local, Year_local, time, period, season,
            Tau, ET, RH, u., jday, co2_flux, ch4_flux, NEE_f,
            Reco, GPP_f, GPP_DT, Reco_DT, FCH4_f, FCH4_gf_RF,
            NEE_f_RF, GPP_f_RF)) %>%
  dplyr::rename(year_local = Year_local)


# function 
plot_daily <- function(data, variable, label, ma = 15) {
  # browser()
  if(ma == 1) {
    data %>% 
    ggplot() +
    geom_line(aes(x = date, y = {{variable}}), col = "navy") +
    labs(x = "year", 
         y = label) +
    # theme(legend.position="none") +
    theme_bw()
  } else {
    data %>% 
    ggplot() +
    geom_point(aes(x = date, y = {{variable}}, col = "daily")) +
    geom_line(aes(x = date, y = rollmean({{variable}}, ma, fill = NA), col = "smoothed")) +
    scale_color_manual(values = c("daily" = "lightblue", 
                                  "smoothed" = "navy")) +
    labs(x = "year", 
         y = label, 
         colour = "") +
    theme_bw()  
  }
}

plot_monthly <- function(main_data, mean_data){
  main_data%>%
  ggplot() +
    geom_bar(aes(x = month, y = value, fill = as.factor(period)), 
             position = position_dodge(), stat="identity") +
    geom_line(data = mean_data, aes(x = month, y = value, group = 1)) +
    geom_point(data = mean_data, aes(x = month, y = value, group = 1)) +
    facet_wrap(vars(variable_lab), ncol = 1,
               scales = "free_y",
               strip.position = "left", 
               # labeller = label_parsed
               ) +
    labs(x = "", y = "", fill = "Year") +
    theme_bw()+
    theme(strip.background = element_blank(),
          strip.placement = "outside") 
}

plot_monthly_anom <- function(main_data, anom_data){
  main_data%>%
  ggplot() +
    geom_bar(data= anom_data, aes(x = month, y = value), 
             position = position_dodge(), stat="identity") +
    geom_line(aes(x = month, y = value, group = 1)) +
    facet_wrap(vars(variable_lab), ncol = 1,
               scales = "free_y",
               strip.position = "left", 
               # labeller = label_parsed
               ) +
    # labs(x = "", y = "", fill = "Year") +
    scale_y_continuous(name = "", 
      sec.axis = sec_axis(~./2, name = "Productivity % of best", 
        labels = "")
      ) +
    theme_bw()+
    theme(strip.background = element_blank(),
          strip.placement = "outside") 
}

# function for setting year period
set_period <- function(data) {
  y_2015_2016 <- data$date >= "2015-10-01" & data$date < "2016-10-01"
  y_2016_2017 <- data$date >= "2016-10-01" & data$date < "2017-10-01"
  y_2017_2018 <- data$date >= "2017-10-01" & data$date < "2018-10-01"
  y_2018_2019 <- data$date >= "2018-10-01" & data$date < "2019-10-01"
  y_2019_2020 <- data$date >= "2019-10-01" & data$date < "2020-10-01"
  y_2020_2021 <- data$date >= "2020-10-01" & data$date < "2021-10-01"
  
  data$period[y_2015_2016] <- "2015-2016"
  data$period[y_2016_2017] <- "2016-2017"
  data$period[y_2017_2018] <- "2017-2018"
  data$period[y_2018_2019] <- "2018-2019"
  data$period[y_2019_2020] <- "2019-2020"
  data$period[y_2020_2021] <- "2020-2021"
  
  data
}

# set season 
set_season <- function(input, date_vector){
  input$month_local <- month(date_vector)
  GS <- input$month_local %in% c(4, 5, 6, 7, 8, 9)
  NGS <- input$month_local %in% c(10, 11, 12, 1, 2, 3)
  input$season <- NA
  input$season[GS] <- "growing season"
  input$season[NGS] <- "non-growing season"
  input
}


```


```{r Data wrangling for fluxes, include = F, message = F, warning = F}
#Conversion factors
ch4_conv <- 12.01/(10^6)
co2_conv <- 12.01/(10^6) 
d.avg <- 1800 * 48  # 60s * 30min * 2 hours * 24 hours

#TO FILTER NON GF DATA TO DAYS WHERE ONLY 60% OR MORE IS PRESENT
daily.nGF <- BB_flux %>%
  dplyr::select(c(year_local, jday, month_local, co2_flux, ch4_flux)) %>%
  drop_na()

obs_count <- daily.nGF %>% 
  group_by(year_local, jday) %>% 
  tally() %>% 
  ungroup()

daily.nGF <- daily.nGF %>%
  group_by(year_local, jday) %>% 
  summarize(co2 = mean(co2_flux),
            ch4 = mean(ch4_flux)) %>%
  mutate(co2gC = co2 * d.avg * co2_conv) %>%
  mutate(ch4gC = ch4* d.avg * co2_conv) %>%
  mutate(ch4mgC = ch4gC * 1000) %>% 
  ungroup() %>% 
  mutate(n = obs_count$n) %>% 
  # filter(n > 48 * 0.6) %>%
  mutate(date = as.POSIXct(paste(year_local, jday, sep = "-"), format = "%Y-%j"))

daily.nGF[which(daily.nGF$n < 48 * 0.3), 2:7] <- NA

  
# daily.nGF$month_local <- as.factor(daily.nGF$month_local)

daily <- BB_flux %>%
  ddply("date", summarize,
            NEE_f = mean(NEE_f),
            NEE_f_RF = mean(NEE_f_RF),
            GPP_DT = mean(GPP_DT),
            GPP_f = mean(GPP_f),
            GPP_f_RF = mean(GPP_f_RF),
            Reco = mean(Reco),
            Reco_DT = mean(Reco_DT),
            CH4_f_RF = mean(FCH4_gf_RF),
            CH4_f = mean(FCH4_f)) %>%
  mutate(NEEgC_f = NEE_f * d.avg * co2_conv, 
         NEEgC_f_RF = NEE_f_RF * d.avg * co2_conv,
         GPPgC_DT = GPP_DT * d.avg * co2_conv, 
         GPPgC_f = GPP_f *d.avg * co2_conv,
         GPPgC_f_RF = GPP_f_RF * d.avg * co2_conv,
         RecogC = Reco * d.avg * co2_conv, 
         RecogC_DT = Reco_DT * d.avg * co2_conv,
         CH4gC_f = CH4_f * d.avg * ch4_conv, 
         CH4mgC_f = CH4gC_f * 1000,
         CH4gC_f_RF = CH4_f_RF * d.avg * ch4_conv,
         CH4mgC_f_RF = CH4gC_f_RF * 1000,
         year_local = year(date), 
         month_local = month(date), 
         floor_date = floor_date(date, "month"))



# set year period
daily <- daily %>% set_period() %>% set_season(date = daily$date)

cumsum <- daily %>% 
  group_by(period) %>% 
  arrange(date) %>% 
  mutate(cumNEE = cumsum(NEEgC_f), 
         cumNEE_RF = cumsum(NEEgC_f_RF),
         cumReco = cumsum(RecogC),
         cumGPP = cumsum(GPPgC_f), 
         cumGPP_RF = cumsum(GPPgC_f_RF),
         cumCH4 = cumsum(CH4gC_f_RF)
         ) %>% 
  ungroup()

monthly <- daily %>% 
   ddply(c("floor_date"), summarize,
        length = length(NEEgC_f),
        NEEgC_f = mean(NEEgC_f) * length, # * length(NEEgC_f) for month^-1
        NEEgC_f_RF = mean(NEEgC_f_RF)* length,
        GPPgC_f = mean(GPPgC_f)* length,
        GPPgC_f_RF = mean(GPPgC_f_RF)* length,
        RecogC = mean(RecogC)* length,
        CH4gC_f = mean(CH4gC_f)* length,
        CH4gC_f_RF = mean(CH4gC_f_RF)* length) %>% 
  mutate(month_local = month(floor_date))

monthly_means <- monthly %>% 
  ddply("month_local", summarize, 
       NEEgC_f = mean(NEEgC_f, na.rm = T),
       NEEgC_f_RF = mean(NEEgC_f_RF, na.rm = T), 
       GPPgC_f = mean(GPPgC_f, na.rm = T),
       GPPgC_f_RF = mean(GPPgC_f_RF, na.rm = T), 
       RecogC = mean(RecogC, na.rm = T),
       CH4gC_f = mean(CH4gC_f, na.rm = T),
       CH4gC_f_RF = mean(CH4gC_f_RF, na.rm = T))
# daily$month_local <- as.factor(daily$month_local)

monthly_anom <- monthly
for(i in 1:nrow(monthly)){ 
  monthly_anom[i, c(3:8)] <- monthly_anom[i, c(3:8)] -  
    monthly_means[monthly$month_local[i], c(2:7)]
  }

# dailyGS <- daily[(daily$jday >= 92 & daily$jday <= 274), ] 
# dailyNGS <-daily[(daily$jday < 92 | daily$jday >=275), ] 


# Cbudget <- daily %>%
#   dplyr::select(c(Site, month_local, jday, CH4mgC_f_RF, CH4gC_f_RF, NEEgC_f)) %>%
#   group_by(Site, month_local) %>%
#   summarise(CH4gCcum = cumsum(CH4gC_f_RF),
#             CH4mgcum = cumsum(CH4mgC_f_RF),
#             NEEgCcum = cumsum(NEEgC_f),
#             NEEgC = NEEgC_f,
#             CH4gC = CH4gC_f_RF,
#             CH4mgC = CH4mgC_f_RF,
#             jday = jday)
```

## Non gap-filled $CO_2$ & $CH_4$ Fluxes 

**Non gap-filled** $CO_2$ & $CH_4$ fluxes. daily fluxes are calculated only from days with at least 60% half-hourly data available. 

```{r, message = F, warning = F}
co2_ngf <- plot_daily(data = daily.nGF, 
                   variable = co2gC, 
                   label = expression("CO"[2]*" flux (gC"*m^{-2}~day^{-1}*")"), 
                   ma = 1
                   )
ch4_ngf <- plot_daily(data = daily.nGF, 
                   variable = ch4gC, 
                   label = expression("CH"[4]*" flux (gC"*m^{-2}~day^{-1}*")"), 
                   ma = 1
                   )
(co2_ngf)
(ch4_ngf)

```

## Gap-filled daily $CO_2$ & $CH_4$ fluxes

```{r, message = F, warning = F}
RecogC <- plot_daily(data = daily, 
                   variable = RecogC, 
                   label = bquote('Reco (g C' ~m^-2~ day^-1*')'), 
                   ma = 1)
GPPgC_f <- plot_daily(data = daily, 
                   variable = GPPgC_f, 
                   label = bquote('GPP (g C' ~m^-2~ day^-1*')'), 
                   ma = 1)
GPPgC_f_RF <- plot_daily(data = daily, 
                   variable = GPPgC_f_RF, 
                   label = bquote('GPP RF(g C' ~m^-2~ day^-1*')'), 
                   ma = 1) 
NEEgC_f <- plot_daily(data = daily, 
                   variable = NEEgC_f, 
                   label = bquote('NEE (g C' ~m^-2~ day^-1*')'), 
                   ma = 1) 
NEEgC_f_RF <- plot_daily(data = daily, 
                   variable = NEEgC_f_RF, 
                   label = bquote('NEE RF(g C' ~m^-2~ day^-1*')'), 
                   ma = 1) 
CH4gC_f <- plot_daily(data = daily, 
                   variable = CH4gC_f, 
                   label = bquote('CH4 (g C' ~m^-2~ day^-1*')'), 
                   ma = 1)
CH4gC_f_RF <- plot_daily(data = daily, 
                   variable = CH4gC_f_RF, 
                   label = bquote('CH4 flux - random forest (g C' ~m^-2~ day^-1*')'), 
                   ma = 1)
(NEEgC_f)
(GPPgC_f)
(RecogC)
(CH4gC_f_RF)
(NEEgC_f_RF)
(GPPgC_f_RF)


GPP_comparison <- daily %>% 
  ggplot() +
    geom_line(aes(x = date, y = GPPgC_f_RF, col = "RF")) +
    geom_line(aes(x = date, y = GPP_f, col = "MDS")) +
    scale_color_manual(values = c("RF" = "blue", 
                                  "MDS" = "black")) +
    labs(x = "year", 
         y = "GPP (gC m-2 day-1)", 
         colour = "")  + 
  theme_bw()

NEE_comparison <- daily %>%
  ggplot() +
    # geom_line(aes(x = date, y = co2gC, col = "nGF"), data = daily.nGF) +
    geom_line(aes(x = date, y = NEEgC_f_RF, col = "RF"), data = daily) +
    geom_line(aes(x = date, y = NEE_f, col = "MDS"), data = daily) +
    scale_color_manual(values = c("RF" = "blue", 
                                  # "nGF" = "blue",
                                  "MDS" = "black")) +
    labs(x = "year", 
         y = "NEE (gC m-2 day-1)", 
         colour = "") +
    theme_bw()

ggplotly(NEE_comparison)
ggplotly(GPP_comparison)

```


## Meteorological variables 

```{r Data wrangling for met variables, include = F, message = F, warning = F}

BB_met <- BB1 %>%  
  rename("TS.5" = "SOIL_TEMP_5CM", 
         "TS.10" = "SOIL_TEMP_10CM",
         "TS.50" = "SOIL_TEMP_50CM") %>% 
  group_by(date) %>% 
  summarize(
      TS.5 = mean(TS.5),  # soil temp
      TS.10 = mean(TS.10),
      TS.50 = mean(TS.50),
      RH = mean(RH_2M),  # relative humidity
      PARin = mean(INCOMING_PAR) * d.avg * 1e-6,  # mol m2 day -1 
      SWin = mean(SHORTWAVE_IN),
      VPD.y = mean(VPD.y),
      VPD.x = mean(VPD.x),
      Precip = sum(PRECIP),
      PA_EC = mean(PA_EC2_AIR),  # barrometric pressure from EC
      PA_2M = mean(PA_2M),  # barrometric pressure from met
      Ta = mean(AIR_TEMP_2M),  # air temp at 2 m
      # WTH2 = mean(4.606 -(-0.89*WTH2+82)/100),  # water table height before 2018
      wtd = mean(WTH_absolute),  # water Marion
      SWC = mean(SVWC) # soil water content
      ) %>%  
  mutate(month_local = month(date), 
         year_local = year(date), 
         floor_date = floor_date(date, "month"))%>%
  ungroup()


# set period
BB_met <- BB_met %>% set_period() %>% set_season(date = BB_met$date)

  
met_monthly <- BB_met %>% 
  ddply("floor_date", summarize, 
      # length = length(TS.5),
      TS.5 = mean(TS.5, na.rm = T),  # soil temp
      TS.10 = mean(TS.10, na.rm = T),
      TS.50 = mean(TS.50, na.rm = T),
      RH = mean(RH, na.rm = T),  # relative humidity
      PARin = mean(PARin, na.rm = T),  #u mol m-2 day-1
      SWin = mean(SWin, na.rm = T),
      VPD.y = mean(VPD.y, na.rm = T),
      Precip = sum(Precip, na.rm = T), # mm per month
      PA_2M = mean(PA_2M, na.rm = T),  # barrometric pressure from met
      Ta = mean(Ta, na.rm = T),  # air temp at 2 m
      SWC = mean(SWC, na.rm = T), 
      wtd = mean(wtd, na.rm = T), 
      min_TS.5 = min(TS.5, na.rm = T), 
      max_TS.5 = max(TS.5, na.rm = T),
      min_wtd = min(wtd, na.rm = T), 
      max_wtd = max(wtd, na.rm = T)) %>%
  mutate(month_local = month(floor_date))

met_monthly_means <- met_monthly %>% 
  ddply("month_local", summarize, 
      TS.5 = mean(TS.5, na.rm = T),  # soil temp
      TS.10 = mean(TS.10, na.rm = T),
      TS.50 = mean(TS.50, na.rm = T),
      RH = mean(RH, na.rm = T),  # relative humidity
      PARin = mean(PARin, na.rm = T),  
      SWin = mean(SWin, na.rm = T),
      VPD.y = mean(VPD.y, na.rm = T),
      Precip = mean(Precip, na.rm = T),
      PA_2M = mean(PA_2M, na.rm = T),  # barrometric pressure from met
      Ta = mean(Ta, na.rm = T),  # air temp at 2 m
      SWC = mean(SWC, na.rm = T), 
      wtd = mean(wtd, na.rm = T), 
      min_TS.5 = min(TS.5, na.rm = T), 
      max_TS.5 = max(TS.5, na.rm = T),
      min_wtd = min(wtd, na.rm = T), 
      max_wtd = max(wtd, na.rm = T))

met_monthly_anom <- met_monthly
# for(i in 1:nrow(met_monthly)){ 
#   met_monthly_anom[i, c(3:14)] <- met_monthly_anom[i, c(3:14)] -  
#     met_monthly_means[met_monthly$month_local[i], c(2:13)]
#   }
for(i in 1:nrow(met_monthly_anom)){
  index <- which(met_monthly_means$month_local == met_monthly_anom$month_local[i])
  met_monthly_anom[i, c(2:13)] <- met_monthly_anom[i, c(2:13)] -
    met_monthly_means[index, c(2:13)]
  # print(i)
  }


```

```{r plotting met variables, message = F, warning = F}

### soil temperature ###

(TS <- TS_no_out %>% 
  # filter(date <= "2020-01-01") %>%
  ggplot() +
  geom_line(aes(x = date, y = TS.5, colour = "5 cm")) + 
  geom_line(aes(x = date, y = TS.10, colour = "10 cm")) +
  geom_line(aes(x = date, y = TS.50, colour = "50 cm")) + 
  scale_color_manual(values = c("5 cm" = "orange1", 
                                "10 cm" = "orangered1", 
                                "50 cm" = "red4"))+
  labs(x = "time", 
       y = expression('Soil temperature ('*~degree*C*')'), 
       colour = "")) + 
  theme_bw()

### relative humidity ###
(RH <- plot_daily(data = BB_met, 
                  variable = RH, 
                  label = "Relative humidity (%)", 
                  ma = 1)) 

### barrometric pressure ###
(PA <- plot_daily(data = BB_met, 
                  variable = PA_2M, 
                  label = "Barrometric pressure (%)", 
                  ma = 1)) 
(SWC <- plot_daily(data = BB_met, 
                  variable = SWC, 
                  label = bquote('soil water content (' ~m^3~ m^-3*')'), 
                  ma = 1))
(Ta <- plot_daily(data = BB_met, 
                  variable = Ta, 
                  label = expression('Air temperature ('*~degree*C*')'), 
                  ma = 1))
(PARin <- plot_daily(data = BB_met, 
                  variable = PARin, 
                  label = expression("PAR ("*mu*"mol"~m^{-2}~s^{-2}*")"), 
                  ma = 1))
(VPD <- plot_daily(data = BB_met, 
                  variable = VPD.y, 
                  label = "VPD", 
                  ma = 1))

(wtd <- BB_met %>% 
  # filter(date <= "2020-01-01") %>%
  ggplot() +
  geom_line(aes(x = date, y = wtd), col = "black") + 
  labs(x = "time", 
       y = "WTD (cm)") + 
  theme_bw())

  
```




# Monthly

## Monthly $CO_2$ & $CH_4$ fluxes

```{r plot monthly fluxes, fig.height = 8, fig.width = 8, message = F, warning = F}
# flux_labels <- c(
#   bquote('NEE (g C' ~m^-2~ day^-1*')'),
#   bquote('GPP (g C' ~m^-2~ day^-1*')'),
#   bquote('Reco (g C' ~m^-2~ day^-1*')'),
#   bquote('CH4 flux - random forest (g C' ~m^-2~ day^-1*')')
# )

flux_labels <- c(
  'NEE (gC m-2 month-1)',
  'GPP (gC m-2 month-1)',
  'Re (gC m-2 month-1)',
  'CH4 flux (gC m-2 month-1)'
)

# monthly_long <- monthly %>%
#   pivot_longer(cols = NEEgC_f_RF:CH4gC_f_RF, names_to = "variable", values_to = "value") %>% 
#   mutate(month = as.yearmon(floor_date),
#          # month_local = factor(month_local, levels = c(1:12)),
#          # month_abb = factor(month.abb[month_local], levels = month.abb), 
#          variable_lab = factor(variable, 
#                            levels = c("NEEgC_f_RF", "GPPgC_f_RF", "RecogC", "CH4gC_f_RF"),
#                            labels = flux_labels))
# 
# monthly_means_long <- monthly_means %>% 
#   pivot_longer(cols = NEEgC_f_RF:CH4gC_f_RF, names_to = "variable", values_to = "value") %>% 
#   mutate(month = as.yearmon(floor_date),
#          # month_local = factor(month_local, levels = c(1:12)),
#          # month_abb = factor(month.abb[month_local], levels = month.abb), 
#          variable_lab = factor(variable, 
#                            levels = c("NEEgC_f_RF", "GPPgC_f_RF", "RecogC", "CH4gC_f_RF"),
#                            labels = flux_labels))
# 
# monthly_anom_long <- monthly_anom %>% 
#   pivot_longer(cols = NEEgC_f_RF:CH4gC_f_RF, names_to = "variable", values_to = "value") %>% 
#   mutate(month = as.yearmon(floor_date),
#          # month_local = factor(month_local, levels = c(1:12)),
#          # month_abb = factor(month.abb[month_local], levels = month.abb), 
#          variable_lab = factor(variable, 
#                            levels = c("NEEgC_f_RF", "GPPgC_f_RF", "RecogC", "CH4gC_f_RF"),
#                            labels = flux_labels))
# 
# ggplotly(plot_monthly(monthly_long, monthly_means_long))

NEE <- daily%>%
ggplot() +
  geom_bar(data = monthly_anom, aes(x = floor_date, y = NEEgC_f_RF/15), fill = "gray", stat = "identity") +
  geom_line(aes(x = date, y = rollmean(NEEgC_f_RF, 7, fill = NA))) +
  scale_y_continuous(
    # limits = c(-4, 2),
    name = expression('NEE (g C' ~m^-2~ d^-1*')'),
    sec.axis = sec_axis(~.*15, name = bquote(Delta*~'NEE (g C' ~m^-2~ month^-1*')'))
    ) +
  labs(x = "") +
  scale_x_date(date_breaks = "1 year",
               date_labels = "%b %Y") +
  theme_bw()

GPP <- daily%>%
ggplot() +
  geom_bar(data = monthly_anom, aes(x = floor_date, y = (GPPgC_f_RF/15)), fill = "gray", stat = "identity") +
  geom_line(aes(x = date, y = rollmean(GPPgC_f_RF, 7, fill = NA))) +
  scale_y_continuous(
    # limits = c(-4, 2),
    name = expression('GPP (g C' ~m^-2~ d^-1*')'),
    sec.axis = sec_axis(~.*15, name = bquote(Delta*~'GPP (g C' ~m^-2~ month^-1*')'))
    ) +
  labs(x = "") +
  scale_x_date(date_breaks = "1 year",
               date_labels = "%b %Y") +
  theme_bw()


Reco <- daily%>%
ggplot() +
  geom_bar(data = monthly_anom, aes(x = floor_date, y = RecogC/25), fill = "gray", stat = "identity") +
  geom_line(aes(x = date, y = rollmean(RecogC, 7, fill = NA))) +
  scale_y_continuous(
    # limits = c(-4, 2),
    name = expression('Reco (g C' ~m^-2~ d^-1*')'),
    sec.axis = sec_axis(~.*15, name = bquote(Delta*~'Reco (g C' ~m^-2~ month^-1*')'))
    ) +
  labs(x = "") +
  scale_x_date(date_breaks = "1 year",
               date_labels = "%b %Y") +
  theme_bw()


CH4 <- daily%>%
ggplot() +
  geom_bar(data = monthly_anom, aes(x = floor_date, y = CH4gC_f_RF/10), fill = "gray", stat = "identity") +
  geom_line(aes(x = date, y = rollmean(CH4gC_f_RF, 7, fill = NA))) +
  scale_y_continuous(
    name = expression(CH[4]~'(g C' ~m^-2~ d^-1*')'),
    sec.axis = sec_axis(~.*10, name = bquote(Delta*~CH[4]~'(g C' ~m^-2~ month^-1*')'))
    ) +
  labs(x = "") +
  scale_x_date(date_breaks = "1 year",
               date_labels = "%b %Y") +
  theme_bw()


# NEE <- daily%>%
# ggplot() +
#   geom_point(data = BB1, aes(x = date, y = NEE_f_RF/10), color = "gray", stat = "identity") +
#   geom_line(aes(x = date, y = rollmean(NEEgC_f_RF, 7, fill = NA))) +
#   scale_y_continuous(
#     # limits = c(-4, 2),
#     name = expression('NEE (g C' ~m^-2~ d^-1*')'),
#     sec.axis = sec_axis(~.*10, name = bquote("NEE ("*mu*~"mol"~m^-2~ s^-1*')'))
#     ) +
#   labs(x = "") +
#   scale_x_date(date_breaks = "1 year", 
#                date_labels = "%b %Y") +
#   theme_bw()
# 
# GPP <- daily%>%
# ggplot() +
#   geom_point(data = BB1, aes(x = date, y = GPP_f_RF/5), color = "gray", stat = "identity") +
#   geom_line(aes(x = date, y = rollmean(GPPgC_f_RF, 7, fill = NA))) +
#   scale_y_continuous(
#     # limits = c(-4, 2),
#     name = expression('GPP (g C' ~m^-2~ d^-1*')'), 
#     sec.axis = sec_axis(~.*5, name = bquote("GPP ("*mu*~"mol"~m^-2~ s^-1*')'))
#     ) +
#   labs(x = "") +
#   scale_x_date(date_breaks = "1 year", 
#                date_labels = "%b %Y") +
#   theme_bw()
# 
# 
# Reco <- daily%>%
# ggplot() +
#   geom_point(data = BB1, aes(x = date, y = Reco), color = "gray", stat = "identity") +
#   geom_line(aes(x = date, y = rollmean(RecogC, 7, fill = NA))) +
#   scale_y_continuous(
#     # limits = c(-4, 2),
#     name = expression('Reco (g C' ~m^-2~ d^-1*')'), 
#     sec.axis = sec_axis(~., name = bquote("Reco ("*mu*~"mol"~m^-2~ s^-1*')'))
#     ) +
#   labs(x = "") +
#   scale_x_date(date_breaks = "1 year", 
#                date_labels = "%b %Y") +
#   theme_bw()
# 
# 
# CH4 <- daily%>%
# ggplot() +
#   geom_point(data = BB1, aes(x = date, y = FCH4_gf_RF/5), color = "gray", stat = "identity") +
#   geom_line(aes(x = date, y = rollmean(CH4gC_f_RF, 7, fill = NA))) +
#   scale_y_continuous(
#     name = expression(F[CH4]~'(g C' ~m^-2~ d^-1*')'), 
#     sec.axis = sec_axis(~.*5, name = bquote(F[CH4]~"("*mu*"mol"~m^-2~ s^-1*')'))
#     ) +
#   labs(x = "") +
#   scale_x_date(date_breaks = "1 year", 
#                date_labels = "%b %Y") +
#   theme_bw()


print(NEE)
ggsave("plots/NEE_daily.png")
print(GPP)
ggsave("plots/GPP_daily.png")
print(Reco)
ggsave("plots/Reco_daily.png")
print(CH4)
ggsave("plots/CH4_daily.png")
```

## Cumulative NEE, GPP, Reco 

```{r}
## plot cumulative 

fluxcum_labels <- c(
  bquote(NEE~'(g C' ~m^-2~')'),
  bquote(GPP~'(g C' ~m^-2~')'),
  bquote(Reco~'(g C' ~m^-2~')'),
  bquote(CH[4]~'(g C' ~m^-2~')')
)

# fluxcum_labels <- c(
#   'Cumulative NEE (gC m-2)',
#   'Cumulative GPP (gC m-2)',
#   'Cumulative Re (gC m-2)',
#   'Cumulative CH4 (gC m-2)'
# )

flux_cum <- cumsum %>% 
  select(c(date, cumNEE_RF, cumGPP_RF, cumReco, cumCH4, period, floor_date)) %>%
  pivot_longer(cols = c(cumNEE_RF, cumGPP_RF, cumReco, cumCH4), names_to = "variable", values_to = "value") %>%
  mutate(variable_lab = factor(variable, 
                           levels = c("cumNEE_RF", "cumGPP_RF", 
                                      "cumReco", "cumCH4"),
                           labels = fluxcum_labels)) %>% 
  group_by(variable,period) %>%
  arrange(date) %>%
  mutate(order = row_number()) %>% 
  ungroup() %>% 
  mutate(day_label = case_when(day(date) == 1L ~ format(date, "%b"),
                     TRUE ~ NA_character_)
         )
  
  
x_break <- flux_cum$order[!is.na(flux_cum$day_label)][1:48]
x_label <- flux_cum$day_label[!is.na(flux_cum$day_label)][1:48]
x_label

flux_cum %>% 
  ggplot(aes(x = order, y = value, color = factor(period), group = factor(period))) + 
  geom_line(size = 1) + 
  facet_wrap(vars(variable_lab), ncol = 1,
               scales = "free_y",
               strip.position = "left", 
               labeller = label_parsed
             ) +
  labs(x = "", y = "", color = "Year") +
  scale_x_continuous(
    breaks = unique(x_break),
    labels = unique(x_label)) +
  theme_bw() +
  theme(strip.background = element_blank(),
        strip.placement = "outside")
ggsave("plots/cumulative_flux.png")
```

## monthly met variables
```{r plot monthly met, fig.height = 10, fig.width = 8, message = F, warning = F} 
# met_labels <- c(
#   bquote(T[s]~'at 5 cm'),
#   # bquote('NEE (g C' ~m^-2~ day^-1*')'),
#   bquote(T[s]~'at 10 cm'),
#   bquote(T[s]~'at 50 cm'),
#   expression('RH("%")'), 
#   expression("PAR ("*mu*"mol"~m^{-2}~s^{-2}*")"), 
#   expression('Incoming~Shortwave'), 
#   expression('VPD'), 
#   expression('Precipitation~(mm)'), 
#   expression('Barrometric~pressure~("%")'), 
#   expression('Air temperature ('*~degree*C*')'), 
#   expression('WTD~before~~2018'), 
#   expression('WTD~after~~2018'), 
#   bquote('soil~water~content~(' ~m^3~ m^-3*')'), 
#   expression('WTD')
#   )

met_labels <- c(
  'Ts at 5 cm (C)',
  # bquote('NEE (g C' ~m^-2~ day^-1*')'),
  'Ts at 10 cm (C)',
  'Ts at 50 cm (C)',
  'RH("%")', 
  "PAR u mol m-2 s-2", 
  'Incoming Shortwave', 
  'VPD', 
  'Precipitation (mm)', 
  'Pa (%)', 
  'Ta (C)', 
  'WTD before 2018', 
  'WTD after 2018', 
  'SWC(m3 m-3)', 
  'WTD (cm)'
  )



TS5cm <- BB_met%>%
ggplot() +
  geom_bar(data = met_monthly_anom, aes(x = floor_date, y = TS.5*5), fill = "gray", stat = "identity") +
  geom_line(aes(x = date, y = rollmean(TS.5, 7, fill = NA))) +
  scale_y_continuous(
    # limits = c(-4, 2),
    name = bquote(T[s~5~cm]~'('*degree*'C)'),
    sec.axis = sec_axis(~./5, name = bquote(Delta*~T[s~5~cm]~'('*degree*'C)'))
    ) +
  labs(x = "") +
  scale_x_date(date_breaks = "1 year", 
               date_labels = "%b %Y") +
  theme_bw()

Tair <- BB_met%>%
ggplot() +
  geom_bar(data = met_monthly_anom, aes(x = floor_date, y = Ta*5), fill = "gray", stat = "identity") +
  geom_line(aes(x = date, y = rollmean(Ta, 7, fill = NA))) +
  scale_y_continuous(
    # limits = c(0, 30),
    name = bquote(T[air]~'('*degree*'C)'),
    sec.axis = sec_axis(~./5, name = bquote(Delta*~T[air]~'('*degree*'C)'))
    ) +
  labs(x = "") +
  scale_x_date(date_breaks = "1 year", 
               date_labels = "%b %Y") +
  theme_bw()

wtd <- BB_met%>%
ggplot() +
  geom_bar(data = met_monthly_anom, aes(x = floor_date, y = wtd*100), fill = "gray", stat = "identity") +
  geom_line(aes(x = date, y = wtd*100)) +
  scale_y_continuous(
    # limits = c(0, 30),
    name = "WTD (cm)",
    sec.axis = sec_axis(~., name = bquote(Delta*~"WTD (cm)"))
    ) +
  labs(x = "") +
  scale_x_date(date_breaks = "1 year", 
               date_labels = "%b %Y") +
  theme_bw()

PARin <- BB_met%>%
ggplot() +
  geom_bar(data = met_monthly_anom, aes(x = floor_date, y = PARin*2), fill = "gray", stat = "identity") +
  geom_line(aes(x = date, y = rollmean(PARin, 7, fill = NA))) +
  scale_y_continuous(
    # limits = c(0, 30),
    name = bquote("PAR ("~mu~mol~m^{-2}~d^{-1}~")"),
    sec.axis = sec_axis(~./2, name = bquote(Delta*~"PAR ("~mu~mol~m^{-2}~d^{-1}~")"))
    ) +
  labs(x = "") +
  scale_x_date(date_breaks = "1 year", 
               date_labels = "%b %Y") +
  theme_bw()

precip <- BB_met%>%
ggplot() +
  geom_bar(data = met_monthly_anom, aes(x = floor_date, y = Precip/10), fill = "gray", stat = "identity") +
  geom_bar(aes(x = date, y = rollmean(Precip, 7, fill = NA)), stat = "identity", fill = "black") +
  scale_y_continuous(
    # limits = c(0, 30),
    name = bquote("Precipitation (mm"~d^-1~")"),
    sec.axis = sec_axis(~.*10, name = bquote(Delta*"Precip (mm"~month^-1~")"))
    ) +
  labs(x = "") +
  scale_x_date(date_breaks = "1 year", 
               date_labels = "%b %Y") +
  theme_bw()

VPD <- BB_met%>%
ggplot() +
  geom_bar(data = met_monthly_anom, aes(x = floor_date, y = VPD.y*2), fill = "gray", stat = "identity") +
  geom_line(aes(x = date, y = rollmean(VPD.y, 7, fill = NA))) +
  scale_y_continuous(
    # limits = c(0, 30),
    name = bquote("VPD (hPa"~d^-1~")"),
    sec.axis = sec_axis(~./2, name = bquote(Delta*~"VPD (hPa"~d^-1~")"))
    ) +
  labs(x = "") +
  scale_x_date(date_breaks = "1 year", 
               date_labels = "%b %Y") +
  theme_bw()

print(TS5cm)
ggsave("plots/TS5cm.png")
print(Tair)
ggsave("plots/Tair.png")
print(wtd)
ggsave("plots/wtd.png")
print(PARin)
ggsave("plots/PARin.png")
print(VPD)
ggsave("plots/vpd.png")
print(precip)
ggsave("plots/precip.png")

ggplotly(water)

```

## Annual 

```{r, message = F, warning = F}

day_count <- daily %>%
  drop_na(c(NEEgC_f_RF, RecogC, GPPgC_f_RF, CH4gC_f_RF)) %>%
  dplyr::count(period)


flux_an_sum <- daily %>%
  group_by(period) %>%
  summarise(NEEgC_f_RF = sum(NEEgC_f_RF, na.rm = T),
            RecogC = sum(RecogC, na.rm = T),
            GPPgC_f_RF = sum(GPPgC_f_RF, na.rm = T), 
            CH4_gC_RF = sum(CH4gC_f_RF, na.rm = T)) %>%
  ungroup() %>%
  mutate(day_count = day_count$n) %>% 
  drop_na()
  # filter(day_count > 200)

# set season 
daily$season <- NA
GS <- daily$month_local %in% c(4, 5, 6, 7, 8, 9)
NGS <- daily$month_local %in% c(10, 11, 12, 1, 2, 3)
daily$season[GS] <- "growing season"
daily$season[NGS] <- "non-growing season"

flux_season_sum <- daily %>%
  group_by(period, season) %>%
  summarise(NEEgC_f_RF = sum(NEEgC_f_RF, na.rm = T),
            RecogC = sum(RecogC, na.rm = T),
            GPPgC_f_RF = sum(GPPgC_f_RF, na.rm = T), 
            CH4_gC_RF = sum(CH4gC_f_RF, na.rm = T)) %>%
  ungroup()%>% 
  drop_na()

met_an_means <- BB_met %>%
  # mutate(year_local = year(date)) %>%
  group_by(period) %>%
  summarise(min_TS.5 = min(TS.5, na.rm = T), 
      max_TS.5 = max(TS.5, na.rm = T),
      min_wtd = min(wtd, na.rm = T), 
      max_wtd = max(wtd, na.rm = T), 
      day_wtd = count(wtd > 0, na.rm = T), 
      day_wtd2 = count(wtd < -0.1, na.rm = T),
      day_precip = count(Precip > 0, na.rm = T), 
      TS.5 = mean(TS.5, na.rm = T),  # soil temp
      TS.10 = mean(TS.10, na.rm = T),
      TS.50 = mean(TS.50, na.rm = T),
      RH = mean(RH, na.rm = T),  # relative humidity
      PARin = sum(PARin, na.rm = T),  
      SWin = mean(SWin, na.rm = T),
      VPD = mean(VPD.y, na.rm = T),
      Precip = sum(Precip, na.rm = T),
      PA = mean(PA_2M, na.rm = T),  # barrometric pressure from met
      Ta = mean(Ta, na.rm = T),  # air temp at 2 m
      SWC = mean(SWC, na.rm = T), 
      wtd = mean(wtd, na.rm = T)) %>%
  ungroup()%>% 
  drop_na()

met_season_sum <- BB_met %>%
  group_by(period, season) %>%
  summarise(min_TS.5 = min(TS.5, na.rm = T), 
      max_TS.5 = max(TS.5, na.rm = T),
      min_wtd = min(wtd, na.rm = T), 
      max_wtd = max(wtd, na.rm = T),
      day_wtd = count(wtd > 0, na.rm = T), 
      day_wtd2 = count(wtd < -0.1, na.rm = T),
      day_precip = count(Precip > 0, na.rm = T), 
      TS.5 = mean(TS.5, na.rm = T),  # soil temp
      TS.10 = mean(TS.10, na.rm = T),
      TS.50 = mean(TS.50, na.rm = T),
      RH = mean(RH, na.rm = T),  # relative humidity
      PARin = sum(PARin, na.rm = T),  
      SWin = mean(SWin, na.rm = T),
      VPD = mean(VPD.y, na.rm = T),
      Precip = sum(Precip, na.rm = T),
      PA = mean(PA_2M, na.rm = T),  # barrometric pressure from met
      Ta = mean(Ta, na.rm = T),  # air temp at 2 m
      SWC = mean(SWC, na.rm = T), 
      wtd = mean(wtd, na.rm = T)) %>%
  ungroup()%>%
  drop_na()

#   
# kable(flux_an_sum, caption = "Cumulative annual fluxes", 
#     col.names = c("year", 
#                   "NEE (gC m^2^ year^-1^)", 
#                   "Reco (gC m^2^ year^-1^)", 
#                   "GPP (gC m^2^ year^-1^)", 
#                   "CH~4~ (gC m^2^ year^-1^)", 
#                   "day_count")) %>% 
# kable_styling()
# 
# kable(met_an_means, caption = "Annual met variables", 
#       col.names = c("year", 
#                     "T~s~~5cm~", 
#                     "T~s~~10cm~",
#                     "T~s~~50cm~", 
#                     "RH(%)", 
#                     "PAR", 
#                     "SW~in~", 
#                     "VPD", 
#                     "Precip", 
#                     "PA", 
#                     "T~a~", 
#                     "SWC",
#                     "WTD")) %>%
# kable_styling()


write.csv(flux_an_sum, "flux_annual_summary.csv")
write.csv(flux_season_sum, "flux_season_summary.csv")
# write.csv(met_an_sum, "met_annual_summary.csv")
write.csv(met_an_means, "met_annual_summary.csv")
write.csv(met_season_sum, "met_season_summary.csv")

```

```{r relative influence of GPP and Reco on NEE variability}
# based on Schaefer et al. (1996)
# f GPP = variance of GPP/(variance of GPP + variance of Reco)

# for annual
var_GPP <- var(flux_an_sum$GPPgC_f_RF)
var_Reco <- var(flux_an_sum$RecogC)
f_GPP <- var_GPP/(var_GPP + var_Reco)
f_Reco <- var_Reco/(var_GPP + var_Reco)

f_GPP; f_Reco


# for growing season
var_GPP_GS <- var(filter(flux_season_sum, season == "growing season")$GPPgC_f_RF)
var_Reco_GS <- var(filter(flux_season_sum, season == "growing season")$RecogC)
f_GPP_GS <- var_GPP_GS/(var_GPP_GS + var_Reco_GS)
f_Reco_GS <- var_Reco_GS/(var_GPP_GS + var_Reco_GS)

f_GPP_GS; f_Reco_GS


# for non-growing season
var_GPP_NGS <- var(filter(flux_season_sum, season == "non-growing season")$GPPgC_f_RF)
var_Reco_NGS <- var(filter(flux_season_sum, season == "non-growing season")$RecogC)
f_GPP_NGS <- var_GPP_NGS/(var_GPP_NGS + var_Reco_NGS)
f_Reco_NGS <- var_Reco_NGS/(var_GPP_NGS + var_Reco_NGS)

f_GPP_NGS; f_Reco_NGS

```


```{r check annual pattern, message = F, warning = F}
# plot_monthly <- function(main_data, mean_data){
#   main_data%>%
#   ggplot() +
#     geom_bar(aes(x = month_abb, y = value, fill = as.factor(year_local)), 
#              position = position_dodge(), stat="identity") +
#     geom_line(data = mean_data, aes(x = month_abb, y = value, group = 1)) +
#     geom_point(data = mean_data, aes(x = month_abb, y = value, group = 1)) +
#     facet_wrap(vars(variable_lab), ncol = 1,
#                scales = "free_y",
#                strip.position = "left", 
#                # labeller = label_parsed
#                ) +
#     labs(x = "", y = "", fill = "Year") +
#     theme_bw()+
#     theme(strip.background = element_blank(),
#           strip.placement = "outside") 
# }


# correlation for annual values
corr <- left_join(met_an_means, flux_an_sum) %>%
  mutate(year = substr(period, 1, 4))

# correlation for growing & non-growing season
corr_GS <- left_join(filter(flux_season_sum, season == "growing season"), filter(met_season_sum, season == "growing season"))%>%
  mutate(year = substr(period, 1, 4))

corr_NGS <- left_join(filter(flux_season_sum, season == "non-growing season"), filter(met_season_sum, season == "non-growing season"))%>%
  mutate(year = substr(period, 1, 4))

corr_an_GS <- left_join(flux_an_sum, filter(met_season_sum, season == "growing season"))%>%
  mutate(year = substr(period, 1, 4))

corr_an_NGS <- left_join(flux_an_sum, filter(met_season_sum, season == "non-growing season"))%>%
  mutate(year = substr(period, 1, 4))




flux_loop <- c("NEEgC_f_RF", "RecogC", "GPPgC_f_RF", "CH4_gC_RF")
met_loop <- c("TS.5", "Ta", "VPD", "wtd", "PARin", "Precip", "GPPgC_f_RF", "min_TS.5", "max_TS.5", "min_wtd", "max_wtd", "PA", "RH", "day_wtd", "day_wtd2", "day_precip")


###### for annual correlation ########
for (i in flux_loop) {
  for (j in met_loop) { 
    eval(parse(text = paste0(i, '_vs_' , j, '<- corr %>% ggplot(aes_string(x = "', j,'", y = "',i,'")) + 
    geom_point(size = 3) + 
  geom_text(aes(label=year), size = 3, hjust=0.5, vjust=-0.8) +
  labs(x = "', j,'", y = "',i,'",  col= "") +  
  theme_bw() + 
  theme(legend.position="none")'
                             )))
    eval(parse(text = paste0("print(",i,"_vs_",j,")")))
    eval(parse(text = paste0("ggsave('plots/nocorr_",i,"_vs_",j,".png')")))
  }
}

## add correlation and regression line
for (i in flux_loop) {
  for (j in met_loop) { 
    eval(parse(text = paste0(i, '_vs_' , j, '<- corr %>% ggplot(aes_string(x = "', j,'", y = "',i,'")) + 
    geom_point(size = 3) + 
  geom_smooth(method = "lm", se = F, col = "black") +
  geom_text(aes(label=year), size = 3, hjust=0.5, vjust=-0.8) +
  labs(x = "', j,'", y = "',i,'",  col= "") +  
  stat_cor(size = 3.5) +
  theme_bw()+ 
  theme(legend.position="none")')))
    eval(parse(text = paste0("print(",i,"_vs_",j,")")))
    eval(parse(text = paste0("ggsave('plots/corr_",i,"_vs_",j,".png')")))
  }
}
  


###### for growing season correlation ########
## add correlation and regression line
for (i in flux_loop) {
  for (j in met_loop) { 
    eval(parse(text = paste0(i, '_vs_' , j, '<- corr_GS %>% ggplot(aes_string(x = "', j,'", y = "',i,'")) + 
    geom_point(size = 3) + 
  geom_smooth(method = "lm", se = F, col = "black") +
  ggtitle("GS") + 
  geom_text(aes(label=year), size = 3, hjust=0.5, vjust=-0.8) +
  labs(x = "', j,'", y = "',i,'",  col= "") +  
  stat_cor(size = 3.5) +
  theme_bw()+ 
  theme(legend.position="none")')))
    eval(parse(text = paste0("print(",i,"_vs_",j,")")))
    eval(parse(text = paste0("ggsave('plots/corr_GS_",i,"_vs_",j,".png')")))
  }
}


###### for non-growing season correlation #####
for (i in flux_loop) {
  for (j in met_loop) { 
    eval(parse(text = paste0(i, '_vs_' , j, '<- corr_NGS %>% ggplot(aes_string(x = "', j,'", y = "',i,'")) + 
    geom_point(size = 3) + 
  geom_smooth(method = "lm", se = F, col = "black") +
  ggtitle("NGS") + 
  geom_text(aes(label=year), size = 3, hjust=0.5, vjust=-0.8) +
  labs(x = "', j,'", y = "',i,'",  col= "") +  
  stat_cor(size = 3.5) +
  theme_bw()+ 
  theme(legend.position="none")')))
    eval(parse(text = paste0("print(",i,"_vs_",j,")")))
    eval(parse(text = paste0("ggsave('plots/corr_NGS_",i,"_vs_",j,".png')")))
  }
}

###### annual flux vs growing season correlation #####
for (i in flux_loop) {
  for (j in met_loop) { 
    eval(parse(text = paste0(i, '_vs_' , j, '<- corr_an_GS %>% ggplot(aes_string(x = "', j,'", y = "',i,'")) + 
    geom_point(size = 3) + 
  geom_smooth(method = "lm", se = F, col = "black") +
  ggtitle("annual flux vs GS variable") + 
  geom_text(aes(label=year), size = 3, hjust=0.5, vjust=-0.8) +
  labs(x = "', j,'", y = "',i,'",  col= "") +  
  stat_cor(size = 3.5) +
  theme_bw()+ 
  theme(legend.position="none")')))
    eval(parse(text = paste0("print(",i,"_vs_",j,")")))
    eval(parse(text = paste0("ggsave('plots/corr_an_vs_GS_",i,"_vs_",j,".png')")))
  }
}

###### annual flux vs non-growing season correlation #####
for (i in flux_loop) {
  for (j in met_loop) { 
    eval(parse(text = paste0(i, '_vs_' , j, '<- corr_an_NGS %>% ggplot(aes_string(x = "', j,'", y = "',i,'")) + 
    geom_point(size = 3) + 
  geom_smooth(method = "lm", se = F, col = "black") +
  ggtitle("annual flux vs NGS variable") + 
  geom_text(aes(label=year), size = 3, hjust=0.5, vjust=-0.8) +
  labs(x = "', j,'", y = "',i,'",  col= "") +  
  stat_cor(size = 3.5) +
  theme_bw()+ 
  theme(legend.position="none")')))
    eval(parse(text = paste0("print(",i,"_vs_",j,")")))
    eval(parse(text = paste0("ggsave('plots/corr_an_vs_NGS_",i,"_vs_",j,".png')")))
  }
}


####### correlation matrix ##########

install.packages("corrplot")
library(corrplot)

source("http://www.sthda.com/upload/rquery_cormat.r")
rquery.cormat(corr[, 2:21])




grid.arrange(ncol = 3, 
             NEEgC_f_RF_vs_PARin, 
             NEEgC_f_RF_vs_Ta, 
             NEEgC_f_RF_vs_TS.5, 
             NEEgC_f_RF_vs_VPD, 
             NEEgC_f_RF_vs_wtd, 
             NEEgC_f_RF_vs_Precip)

grid.arrange(ncol = 3, 
             RecogC_vs_PARin, 
             RecogC_vs_Ta, 
             RecogC_vs_TS.5, 
             RecogC_vs_VPD, 
             RecogC_vs_wtd, 
             RecogC_vs_Precip)

grid.arrange(ncol = 3, 
             GPPgC_f_RF_vs_PARin, 
             GPPgC_f_RF_vs_Ta, 
             GPPgC_f_RF_vs_TS.5, 
             GPPgC_f_RF_vs_VPD, 
             GPPgC_f_RF_vs_wtd, 
             GPPgC_f_RF_vs_Precip)

grid.arrange(ncol = 3, 
             CH4_gC_RF_vs_PARin, 
             CH4_gC_RF_vs_Ta, 
             CH4_gC_RF_vs_TS.5, 
             CH4_gC_RF_vs_VPD, 
             CH4_gC_RF_vs_wtd, 
             CH4_gC_RF_vs_Precip)


```

```{r daily pattern}

daily.nGF <- left_join(daily.nGF, BB_met)
daily.nGF <- daily.nGF %>% drop_na()

daily.nGF %>% ggplot(aes(x = TS.5, y = ch4gC)) + 
  geom_point() + 
  geom_smooth(method = "loess", se = F)

colnames(daily)
colnames(BB_met)

daily_met_flux <- left_join(daily, BB_met) 

daily_met_flux %>% 
  filter(TS.5 > 18) %>%
  ggplot(aes(x = wtd, y = CH4gC_f_RF)) + 
  geom_point() + 
  geom_smooth(method = "loess", se = F, span = 1)

```

```{r HOS approach}



```


```{r compare two WTD types}

## check which WTD correction type makes more sense

# plot wtd2 vs wtd
corr %>% ggplot(aes(x = wtd, y = wtd2)) + 
    geom_point(aes(col = factor(period), label = factor(period)), size = 3) + 
  geom_smooth(method = "lm", se = F, col = "black") +
  labs(x = "wtd", y = "wtd2",  col= "") +  
  stat_cor(size = 3.5) +
  theme_bw()

# plot wtd vs precip
corr %>% ggplot(aes(x = wtd, y = Precip)) + 
    geom_point(aes(col = factor(period), label = factor(period)), size = 3) + 
  geom_smooth(method = "lm", se = F, col = "black") +
  labs(x = "wtd", y = "precip",  col= "") +  
  stat_cor(size = 3.5) +
  theme_bw()

# plot wtd2 vs precip
corr %>% ggplot(aes(x = wtd2, y = Precip)) + 
    geom_point(aes(col = factor(period), label = factor(period)), size = 3) + 
  geom_smooth(method = "lm", se = F, col = "black") +
  labs(x = "wtd2", y = "precip",  col= "") +  
  stat_cor(size = 3.5) +
  theme_bw()


# plot wtd vs SWC
corr %>% ggplot(aes(x = wtd, y = SWC)) + 
    geom_point(aes(col = factor(period)), size = 3) + 
  geom_smooth(method = "lm", se = F, col = "black") +
  labs(x = "wtd", y = "SWC",  col= "") +  
  stat_cor(size = 3.5) +
  theme_bw()

# plot wtd2 vs SWC
corr %>% ggplot(aes(x = wtd2, y = SWC)) + 
    geom_point(aes(col = factor(period)), size = 3) + 
  geom_smooth(method = "lm", se = F, col = "black") +
  labs(x = "wtd2", y = "SWC",  col= "") +  
  stat_cor(size = 3.5) +
  theme_bw()



# plot daily wtd vs SWC
BB_met %>% 
  filter(period == "2016-2017") %>%
  ggplot(aes(x = wtd, y = SWC)) + 
  geom_point() +
  geom_smooth(method = "lm", se = F, col = "black") + 
  labs(x = "daily wtd", y = "daily SWC", col = "") + 
  stat_cor(size = 3.5) + 
  theme_bw()

# plot timeseries of SWC & WTD
plot_ly(data = BB_met, x = ~date, y = ~SWC, name = 'SWC', type = 'scatter', mode = 'lines') %>%
  add_trace( x = ~date, y = ~wtd, name = 'wtd', type = 'scatter', mode = 'lines') %>% 
    add_trace( x = ~date, y = ~wtd2, name = 'wtd', type = 'scatter', mode = 'lines') 


###### for Growing season ####

# plot wtd2 vs wtd
corr_GS %>% ggplot(aes(x = wtd, y = wtd2)) + 
    geom_point(aes(col = factor(period), label = factor(period)), size = 3) + 
  geom_smooth(method = "lm", se = F, col = "black") +
  labs(title = "growing season", x = "wtd", y = "wtd2",  col= "") +  
  stat_cor(size = 3.5) +
  theme_bw()

# plot wtd vs precip
corr_GS %>% ggplot(aes(x = wtd, y = Precip)) + 
    geom_point(aes(col = factor(period)), size = 3) + 
  geom_smooth(method = "lm", se = F, col = "black") +
  labs(title = "growing season", x = "wtd", y = "precip",  col= "") +  
  stat_cor(size = 3.5) +
  theme_bw()

# plot wtd2 vs precip
corr_GS %>% ggplot(aes(x = wtd2, y = Precip)) + 
    geom_point(aes(col = factor(period)), size = 3) + 
  geom_smooth(method = "lm", se = F, col = "black") +
  labs(title = "growing season", x = "wtd2", y = "precip",  col= "") +  
  stat_cor(size = 3.5) +
  theme_bw()

# plot wtd vs SWC
corr_GS %>% ggplot(aes(x = wtd, y = SWC)) + 
    geom_point(aes(col = factor(period)), size = 3) + 
  geom_smooth(method = "lm", se = F, col = "black") +
  labs(x = "wtd", y = "SWC",  col= "") +  
  stat_cor(size = 3.5) +
  theme_bw()

# plot wtd2 vs SWC
corr_GS %>% ggplot(aes(x = wtd2, y = SWC)) + 
    geom_point(aes(col = factor(period)), size = 3) + 
  geom_smooth(method = "lm", se = F, col = "black") +
  labs(x = "wtd2", y = "SWC",  col= "") +  
  stat_cor(size = 3.5) +
  theme_bw()




###### for Non-Growing season ####

# plot wtd2 vs wtd
corr_NGS %>% ggplot(aes(x = wtd, y = wtd2)) + 
    geom_point(aes(col = factor(period), label = factor(period)), size = 3) + 
  geom_smooth(method = "lm", se = F, col = "black") +
  labs(title = "non-growing season", x = "wtd", y = "wtd2",  col= "") +  
  stat_cor(size = 3.5) +
  theme_bw()

# plot wtd vs precip
corr_NGS %>% ggplot(aes(x = wtd, y = Precip)) + 
    geom_point(aes(col = factor(period), label = factor(period)), size = 3) + 
  geom_smooth(method = "lm", se = F, col = "black") +
  labs(title = "non-growing season", x = "wtd", y = "precip",  col= "") +  
  stat_cor(size = 3.5) +
  theme_bw()

# plot wtd2 vs precip
corr_NGS %>% ggplot(aes(x = wtd2, y = Precip)) + 
    geom_point(aes(col = factor(period), label = factor(period)), size = 3) + 
  geom_smooth(method = "lm", se = F, col = "black") +
  labs(title = "non-growing season", x = "wtd2", y = "precip",  col= "") +  
  stat_cor(size = 3.5) +
  theme_bw()

```



```{r read remote sensing indices}

# read csv exported from GEE
RS_indices <- read.csv("G:/My Drive/Burns_Bog/BB1_GEE_Indices.csv", header = T, skip = 1) %>% 
  select(-1)

# get date from landsat ID
RS_indices$date <- RS_indices$id %>% 
  substr(13, 20) %>%
  as.POSIXct(format = "%Y%m%d")

RS_indices_daily <- RS_indices %>%
  filter(latitude >= 49.128682195765705 & latitude <= 49.13011436654678) %>%
  filter(longitude >= -122.98623037567138 & longitude <= -122.98365545501709) %>%
  ddply("date", summarize, 
        MNDWI_SW1 = mean(MNDWI_SW1, na.rm = T), 
        MNDWI_SW2 = mean(MNDWI_SW2, na.rm = T), 
        NDVI = mean(NDVI, na.rm = T), 
        NDWI = mean(NDWI, na.rm = T), 
        NDWI_gao = mean(NDWI_gao, na.rm = T), 
        LST = mean(CELSIUS, na.rm = T))

daily_for_RS <- left_join(daily, BB_met) %>% 
  select(date, NEE_f_RF, GPP_f_RF, Reco, CH4gC_f_RF, 
         TS.5, TS.10, Precip, Ta, wtd,
         period, season, year_local, month_local) %>%
  mutate(
  NEE_7 = rollmean(NEE_f_RF, 7, fill = NA), 
  GPP_7 = rollmean(GPP_f_RF, 7, fill = NA), 
  Reco_7 = rollmean(Reco, 7, fill = NA), 
  CH4_7 = rollmean(CH4gC_f_RF, 7, fill = NA),
  TS.5_7 = rollmean(TS.5, 7, fill = NA), 
  Precip_7 = rollmean(Precip, 7, fill = NA), 
  Ta_7 = rollmean(Ta, 7, fill = NA), 
  wtd_7 = rollmean(wtd, 7, fill = NA))


RS_indices <- left_join(RS_indices_daily, daily_for_RS) %>% drop_na()


# calculate annual RS indices (mean, peak, median)
RS_indices %>% 
  plot_ly(x = ~date, y = ~NDVI, type = "scatter", mode= "lines", name = "NDVI") %>% 
  add_trace(y =~NDWI_gao, type = "scatter", mode = "lines", name = "NDWI") %>% 
  add_trace(y =~GPP_7, type = "scatter", mode = "lines", name = "GPP_7") %>% 
  add_trace(y =~LST, type = "scatter", mode = "lines", name = "LST") %>% 
  add_trace(y =~Ta_7, type = "scatter", mode = "lines", name = "Ta_7")


RS_indices %>% 
  plot_ly(x =~NDVI, y =~GPP_7, type = "scatter", mode = "markers")

```


```{r, eval = F, include = F}
# check with Nick 

# Nick <-  daily %>% 
#   filter(date >= "2015-06-16" & date <= "2016-06-15") %>%
#   group_by(year_local, month_local) %>% 
#   summarize(NEEgC_f = sum(NEEgC_f),
#         RecogC = sum(RecogC),
#         GPPgC_f = sum(GPPgC_f), 
#         CH4_gC = sum(CH4gC_f)) %>% 
#   ungroup()
# sum_Nick <- sum(as.numeric(Nick$GPPgC_f))
# sum_Nick /12 * 44

```

```{r, eval = F, include = F}

# Check with Marion 


Marion <- daily %>% 
  filter(year_local == 2020) %>% 
  mutate(cumNEE = cumsum(NEEgC_f), 
         cumReco = cumsum(RecogC),
        cumGPP = cumsum(GPPgC_f), 
        cumCH4 = cumsum(CH4gC_f))
plot_daily(data = Marion, 
           variable = cumNEE, 
           label = expression("cumulative NEE (gC "*m^{-2}~day^{-1}*")"), 
           ma = 1
           )
plot_daily(data = Marion, 
           variable = cumReco, 
           label = expression("cumulative Reco (gC "*m^{-2}~day^{-1}*")"), 
           ma = 1
           )
plot_daily(data = Marion, 
           variable = cumGPP, 
           label = expression("cumulative GPP (gC "*m^{-2}~day^{-1}*")"), 
           ma = 1
           )
plot_daily(data = Marion, 
           variable = cumCH4, 
           label = expression("cumulative CH4 (gC "*m^{-2}~day^{-1}*")"), 
           ma = 1
           )
```



